* 拢（攏） 凑起，总合：拢共。拢总。归拢。 ⒉ 靠近，船只靠岸：拢岸。拉拢。 ⒊ 使不松散或不离开：收拢。拢音。把孩子拢在怀里。 ⒋ 梳，用梳子整理头发：拢一拢头发。 ⒌ 合上，聚集：她笑得嘴都合不拢了。

荼蘼: 春末之花，三春将尽,
荼䕷花开代表女子的青春已成过去。荼䕷花开，表示感情的终结。爱到荼靡，意蕴生命中最灿烂、最繁华或最刻骨铭心的爱即将失去。
荼䕷是一种伤感的花。荼䕷花是春天最后开花的植物，它开了也就意味着春天结束了，“三春过后诸芳尽”，开花的季节也就结束了。花开总是形容女子的青春将逝，或是感情到了尽头
韶华胜极
 
塑料棋盘却搁不下

但王一生的大名，却常被班上几个棋篓子供在嘴上

逸闻鄙事

怔

我有点儿不耐烦。讲老实话，我不太愿意复述这些事情，尤其是细节。我觉得这些事情总在腐蚀我，它们与
我以前对生活的认识太不合辙，总好像是在嘲笑我的理想

忧’这玩意儿，是他妈文人的佐料儿。我们这种人，没
有什么忧，顶多有些不痛快。何以解不痛快？唯有象棋

呷
为棋不为生’，为棋是养性，生会坏性，所以生不可太盛。
锅底蓄上水

这里屋外常有一二处小丛的野茴香，我就拔来几棵，揪在汤里，立刻屋里异香扑鼻。大家这时饭已吃净，纷纷舀了汤在
碗里，热热的小口呷，不似刚才紧张，话也多起来了。

走出十多步，王一生有些不安，但也只是暗暗捻一下手指

油灯下，王一生抱了双膝，锁骨后陷下两个深窝，盯着油灯，时不时拍一下身上的蚊虫

脚卵穿了破衣服，肩了锄来送
觉得日光晃眼
窗台上摆了一溜儿花草

只见三四个女的，穿着蓝线衣裤，胸蹶得不能再高，一扭一扭地走过
来，近了，并不让路，直脖直脸地过去。我们赶紧闪在一边儿，都有点儿脸红

这时已近傍晚，太阳垂在两山之间，江面上便金子一般滚动，岸边石
头也如热铁般红起来。有鸟儿在水面上掠来掠去，叫声传得很远。对岸有人
在拖长声音吼山歌，却不见影子，只觉声音慢慢小了

一个人走到台边，对着空空的座位一敬礼，尖着嗓子学报幕员，说：“下一
个节目——睡觉。现在开始。”大家悄悄地笑，纷纷钻进幕布躺下了

四五条狗窜来窜去

我心里忽然有一种很古的东西涌上来，喉咙紧紧地往上走。读过的书，
有的近了，有的远了，模糊了。平时十分佩服的项羽、刘邦都目瞪口呆，倒
是尸横遍野的那些黑脸士兵，从地下爬起来，哑了喉咙，慢慢移动。一个樵
夫，提了斧在野唱。

发噱: 引人发笑

王一生孤身一人坐在大屋子中央，瞪眼看着我们，双手支在膝上，铁
铸一个细树椿，似无所见，似无所闻。高高的一盏电灯，暗暗地照在他脸上，
眼睛深陷进去，黑黑的似俯视大千世界，茫茫宇宙。那生命像聚在一头乱发
中，久久不散，又慢慢弥漫开来，灼得人脸热。

夜黑黑的，伸手不见五指。王一生已经睡死。我却还似乎耳边人声嚷
动，眼前火把通明，山民们铁了脸，肩着柴禾林中走，咿咿呀呀地唱。我笑
起来，想：不做俗人，哪儿会知道这般乐趣？家破人亡，平了头每日荷锄，
却自有真人生在里面，识到了，即是幸，即是福。衣食是本，自有人类，就
是每日在忙这个。可囿在其中，终于还不太像人。倦意渐渐上来，就拥了幕
布，沉沉睡去。
