* 思维转变
1你想什么事都准备妥当了再去做，哪有这种好事，你还以为你在学校啊，准备一个学期再来考试，门都没有。
谁是一开始就什么都会的，都是边做边学的，根本就没有时间给你准备，机会是不等人的。你不懂可以去问别人，你可以找人帮你，你看那谁不就到处找人帮忙吗，你闷在那里纠结是不行的。”
原文记不太清楚了，意思大致如此。这番话给了我很大的启发，甚至可以说是颠覆性的。
在这之后，我开始尝试着去硬着头皮接下一些自己不太熟的业务，边学边做，不懂的，就找人请教。
虽然一开始做的并不好，甚至有些项目还搞砸了，但这过程中，我的能力得到了肉眼看得见的提升，各方面都得到了极大的成长。
<b>这就是我的第一个思维转变：<br><br>永远不要等着准备好了再去做，机会是不等人的，边学边做才是最快的成长方法。</b>

2 以前我以为只要在那想，就能想清楚。后来随着阅历增多，年龄渐长，慢慢的就发现，很多以前想不明白的，其实不需要想，你看见了，就懂了。
现在，我已经很少去想那些没什么意义的东西了。确定好自己的目标，然后多做事，多看书。想不明白的，就不再去想，就算想，也不要停下来想，要边做边想，边读边想，这样才是高质量的思考。
<b>这就是我的第二个思维转变：<br><br>你的问题就在于读书太少而想的太多，永远不要在无意义的思考上耗费太多时间，多读书，多行动，只有在知识和阅历增长之后，你的思考才会更有价值。</b>


3. 我的工作很辛苦，难度 也高，但赚的钱却不如一些没我辛苦的同学。
有一天，我家里电线坏了，就打电话找来维修师傅。那次坏的很严重，电线抽不出来，要重新打洞铺线才行，反正两个维修师傅忙活了很久，最后加上新的电线之类的材料钱，以及两个人忙活了半天的工钱，也才一共200。
他们比我更辛苦，而且也并不是完全没有技术含量，但赚的钱却比我少太多。
这时我忽然想明白，你赚钱的多少，与你的劳动强度，技能水平，有关系，但都不大。
关键在于你的不可替代性，以及你所在的平台，你的行业。
我有年薪百万的投行朋友，也有年薪40~50万的程序员朋友，也有年薪10万的传统行业朋友，他们都是高材生，精英，也都非常努力，但收入却天差地别。
这就是行业的区别！
选对行业非常重要。当然，工作的意义并非收入一个衡量维度，但收入始终是非常重要的一个维度，而且在一个新兴的，有朝气的，精英聚集的行业，从哪方面来说，都会是更好的选择。
另外，提升自己的不可替代性也非常重要。
如果你的工作分分钟可以被一个实习生替代，那老板为什么要给你那么高的薪水？
只有你变得不可替代了，你的议价能力才能提高。
不可替代性其实包括很多，一种是你业务水平的提升，一种是你是复合型人才，另外一种是积累人脉。
提高业务水平很容易理解，就是不断提升你的专业水准。
而复合型，则指的是，能够将两种或多种不同的技能进行融合，从而产生新的技能。
举个简单的例子，比如你拥有较强的写作能力，同时又对电影非常有研究，那你就可以去写影评，在知乎、豆瓣、微信公众号发表，很容易就成为所谓大V。
具体如何组合，哪些可以组合，大家可以结合自己的优势去思考，总之，不同技能的融合，可以让你变得独特，且不可替代。
另外，人脉也是一种稀缺资源。
比如，你与某个人认识，但并不算多深厚的交情，但要谈合作的话，和他完全不熟的人相比，还是有着很大区别的，他更愿意相信你，且可能会给更优惠的条件。
很多时候，我们身处在一个行业内，会觉得很多东西都是理所当然的，并不是那么宝贵。但要知道，行业外的人，想要找到合适的人办事，经常是求告无门的。
当你在一个行业足够久了，你的行业人脉将变得不可替代。尤其是一些管理岗位，大部分的工作都需要协作，需要你去调动资源，而只有掌握了人脉的人，才能做成这种事，这不是一个实习生可以替代的了的。
这里，我的建议是，三种都需要兼顾，不能只闷头发展一种。不要有太大的短板，否则在未来，你很容易因市场或政策的改动而变得被动。
<b>这就是我的第三个思维转变：<br><br>你的赚钱能力与你的专业水平及劳动强度关系不大，更重要的是你所在的行业、平台和你的不可替代性。想要在职场中获得更好的发展，想要赚更多的钱，只有去提高自己的不可替代性，这也是应对未来市场、政策变数的唯一方法

1. 不要轻易说不，要积极思考可能性。(自己体验卫生巾,没有脱胶，说服客户不退单).

2."我老公原来就是不知道打人的严重性，被你们公安局罚过一回，后来有前科找工作都不好找，现在又是积分落户，我不想这么整他的呀！
我让他赔点儿钱是给他一个台阶下，我想着一百块钱也不多吧？”“你怎么不早说呀？”“我想的是我这一巴掌也不能白挨啊！你说
说，一个大男的扇了女孩子一大耳贴子，赔一百块钱多吗？不就是一个意思吗？"
----即使不能够理解他们内心的想法，也应该去听，去想，去尝试感受。因为你面对不仅仅是一张脸一张嘴，而是一个完整的人

 1.开场好不算什么，结局稳才是赢家。
没有恒常，只有无常，幼时我以为有钱的人永远有钱有权的人永远有权有颜的人永远有颜，之后再观同一人时早已换了天地，且出于不可逆因素，会永恒跌落，然而这其中不过二十年。
从那一刻起我就明白：
（1）人生如寄，万事皆体验；
（2）当下拥有需知足，皆是命运眷顾；
（3）不妄念永恒上升，岁岁无忧已是大福气；
（4）他人因自有他人果，不妒忌不攀比只慎重自身因果；
（5）开场好不算什么，结局稳才是赢家。<h2><b>2.感恩接纳是最好的回馈。</b></h2>
任何关系中，如若对方心甘情愿为自己付出，你要做的并非惊慌失措全推开，亦非深感不安想着立马回报，而是给他这份付出予以接纳与肯定，你因他的付出感到开心快乐就是给他的最好回馈，爱你的人会因为你的开心而开心。<h2><b>3.无态度亦是态度，无想法亦是想法。</b></h2>
所谓真实的自己，不一定要铁骨铮铮态度分明。
如若自己处于毫无利益冲突的群体中，对人云亦云不感兴趣，就应学会坦诚接纳自己的“不感兴趣”，无态度亦是态度，无想法亦是想法，你只要坚持这个真实的自己，接纳自己的偶尔沉默与断片，允许自己不必八面玲珑，才会收获契合人际，才算得是真正意义上的从心出发来去自如，强行表态假装迎合不但消耗自己，亦会迎来虚假人际。<h2><b>4.基于他人为他人目标，从己出发方是自己目标。</b></h2>
迎合他人眼光所制定的目标往往是他人目标，如此不仅容易迷失心之所向，且会因难以实现目标而自我怀疑。
所以制定目标需基于：
（1）自己脚踏实地可实现；
（2）从自己当下所拥有处发掘；
（3）关注点在自身，并非妄想寄居于外境变幻来成全自己。目标本身没有高下之分，从你自己当下局面出发的才是属于自己的目标。<h2><b>5.幸福与自在是殊途同归的旅程。</b></h2>
别人通往开心的途径可能需共生于关系、依托于世俗，但如若自己无法从中收获自在满足，则说明这并非自己的幸福路径。你不一定要限于某条独木桥才会幸福，适合自己的阳关道一定能让你从中获得滋养与进步，这个你是能感知的。<h2><b>6.旁人异路，是自己正确归途的反面映照。</b></h2>
任何一种人格并没有绝对的好与坏。
他人与自己的不相同，不是来提醒你如何化身泛泛之辈，而是来点醒你，让你清楚认知这并非适合自己的人生模式，继而更加坚定自己的心之所向。如若在这个过程中立场摇摆，人云亦云，掩埋自我，就会在他人剧本中流离失所，直到你怀疑、认栽、自省、才会重新站起自我接纳，继而更加坚定尊重自己的真实人格，忠贞不渝地守护自己与生俱来的珍贵天性。毕竟，不尝试过不走岔路终究意难平，以为世俗接纳的才是正确路途。<h2><b>7.每个人所选皆是出于他立场的量心定做。</b> </h2>
为了别人的选择而惋惜，或因他人抱怨而圣母心泛滥时，必须要时刻明确，每一个人的自愿选择都是愿打愿挨自作自受，他不情愿，任何事情都不可能藕断丝连持续发展，因此没有必要将自己过度共情于他人黯淡中，大家都是独立个体。<h2><br></h2><h2><b>8.他人给出他人果，自己接受自己因。</b></h2>
别人给自己的“果”于自己而言只是一个新的“因”，他们对自己的影响，只能止步于“给”的那一刻，至于自己的“果”如何，取决于自身选择，是自己的事情，不要颠倒主客，将自身“果”共生于他人“果”。<h2><br></h2><h2><b>9.所处当下即是自身立场。</b></h2>
自己所选的一切，或当下所处境地，即是内心投影或锻炼契机，如若不可逆转，最有利于自己的方式就是尽好当下角色义务，勇敢承担分内责任，唯有不逃避不放弃接受它面对它攻破它，完成当下课题，才能过关升级迎来新的契机与境地，盲目抱怨，即是站在自身对立面与己抗衡，不仅无补于事，亦会造成内耗。<h2><br></h2><h2><b>10.局限于时间容易被时间所局限。</b></h2>
一个人如果过度将自己所求局限于规定时间中，如年入定要达到多少，如某年龄定要如何，就会容易因这份局限而忽略此前幸运所得或造成虚幻恐惧。
实则，把时间线放长，一人某个时段的获得可能足以让他往后无忧，认为自己会一直走红永处巅峰不过是贪心不足蛇吞象。当你把这些无法达成所愿的虚高标准回归现实，就会发现，哪怕没达标，你还是好好的，还是有能力为自己兜底。自己的心安处一定要基于当下拥有处，而非盲目与时间赛跑。<h2><b>11.赏识非施舍，而是同频人伸出的橄榄枝。</b></h2>
他人赏识，不是“看得起”你，是认为你和他同频。不应受宠若惊，不要深感不配，不能卑微推辞，而是要感恩命运安排，让你遇见了惺惺相惜的同频人。<h2><br></h2><h2><b>12.时机未到，潜龙勿用，时机一到，乘风而起。</b></h2>
是你的机会还迟迟不来，要不就是你还需精进，要不就是机会本身还差火候，两者都是时机未到，你唯一能做的是，做好自己，等风来。

* 焦虑
活得太焦虑，只有一个原因，你把人生过反了
王阳明是个牛人，很多企业家都喜欢研究他。
认识个朋友，长期研究王阳明的书籍和语录，就靠这一招，一年能赚40多万。
王的理论中，最重要的一点，就是知行合一。
很多人听过这话，但也许理解有点偏差。
什么是知行合一呀？
关键就在于这个知，不是知道的意思，而是良知。
简单来说，就是我们做事情，要跟着良知走，要表里如一。
以前很多的哲学家，都认为世界是心生的，心生万物嘛。
举个例子，我现在对着电脑打字，是因为心里有了电脑，这个电脑才存在。
如果心里没电脑，那这个电脑就是不存在的。
一句话，意识决定物质。
不过现在物质决定意识占据主流，也被更多人认可。
我们不管哪个正确，因为谁对谁错，都不重要，关键是你从知行合一中，能领悟到什么。
如何去现实社会中变现，赚取财富，才是最重要的。
1、生活太焦虑。
有个朋友，去年生了二胎。
现在的她，特别的烦躁。
不但要给大女儿做饭，还要给小儿子喂奶。
本来她想生完娃了，就让父母帮着带，她要去上班的。
可父母由于疫情的原因，没回家过年，现在已经开工，至少今年不能帮助带娃了。
每次想到这些事情，她都气不打一处来，很想发火。
给女儿做饭时，想着等会要给儿子喂奶。
给儿子喂奶时，想着还有一堆衣服没洗。
现实生活中，很多人跟她一样，无时无刻不处于焦虑之中。
吃饭时，忙着玩手机，不知道饭菜什么口味。
上着班，在想下班后吃什么，根本不能安心工作。
出去旅游一趟，一直在郁闷买了高价产品，完全忽略了沿途的风景。
这样的生活，能不焦虑，烦躁吗？
2、做什么，专注什么。
有次，和朋友爬山。
爬了20多分钟，累得气喘吁吁，衣服都湿透了。
支撑我们的念头，就是想看看山顶的风景，一定很美吧。
结果？
到山顶一看，确实美，但也就兴奋了不到2分钟，感觉就没意思了。
爬山的真正意义在哪？
不是为了享受山顶那2分钟，而是在爬山的过程，体验虚脱的感觉，想放弃的冲动，咬牙坚持的韧劲。
这种心理变化，才是对爬山之人，改变最大的。
可很多人怎么做的？
就为了去山顶拍张照，发个朋友圈，证明自己曾经来过！
人生，也是如此。
吃饭的时候，就好好品尝美食的味道。
上班的时候，就全力以赴做好手上的工作。
旅游的时候，就尽情享受沿途的大好风景。
做什么，专注什么就行了。
3、赚钱的秘密。
很多人想赚钱，但和爬山差不多，只盯着最后的结果，只想我要一年挣30万。
但中间应该怎么做，要做哪些工作，付出多少辛苦，却完全不上心。
抱着这样的想法，自然很难真正赚到钱。
董明珠有次采访中说，她的想法很简单，做销售员的时候，就准备一辈子卖空调了。
只要自己足够努力，总有一天能成为销冠。
那时的她，根本不会想着当什么董事长，成为一家大型集团的一把手。
前几年，和一群同事创业，大家很少去想今后能赚多少钱，只想着多学点东西，涨涨本事。
几年下来，大家都赚了不少，也都买了不错的房子。
手里有点钱后，有朋友找了个项目，大家一合计，想玩把大的，一人出几万，投了进去。
最后泡都没冒个，全部打了水漂。
有个很简单的道理，你眼里只盯着钱的时候，是很难赚到钱的。
一心想着把事情做好，钱反而会向你靠拢。
有人可能会说这是鸡汤，嗯，也许吧，经历过就会懂了。
这个世界，本身就是充满意外和不确定的，想得太过完美，必然带来失望，产生抱怨。
如果，我们坦然面对一切好与坏，把精力放在享受过程上，是不是会少很多痛苦？
当你接受痛苦时，就没什么能让你痛苦。
当你接受失去时，就没什么能让你失去。
因为你知道，一切都是正常的！
