* Many knowledge of different areas could have the same model, with some adjustments. Try to build highways among them.
* Method One: Visceralization
A model isn’t a grouping of ideas, it’s an experience
The best “visceralizations” are combinations of images, sounds, feelings and textures.  Depending on your learning 
preference you may see, hear or feel ideas.  More than just a picture, you want an experience
  Think of visceralizing like your brains version of zipping a file. 
 Visceralizing means taking a handful of concepts and turning them into a single workable experience

* holistic learning
That different strategy I called holistic learning.  I call it holistic learning because it 
challenges you to view learning as a comprehensive whole, instead of a list of 
memorized facts.  Smart people tend to make fewer distinctions between branches of 
knowledge and can easily relate one set of understandings to another.  
By learning holistically, smart people are able to quickly integrate new 
information.  More importantly, this information sticks.  They actually “get” the 
concepts and see how the concepts relate to far more than just the problems given.
* flow-note-taking
** Listening Isn't a Passive Activity
People like to draw lines between listening and practice. As if, 
in a lecture, they are passively absorbing knowledge, and when 
Flow-Based Notetaking writing an essay or doing problem sets, they are actively 
practicing it. Flow-based notetaking turns this formula on its head, by 
putting the listener in an active role, creating connections instead of just absorbing them.
**  organize it spatially with arrows connecting ideas.
4P's
mapping out the ideas is only the most basic part of flow-based notetaking
** Write things in your own words, not the lecturers. If you 
can’t describe something in alternate terms, you 
probably don’t adequately understand the original 
terms.
** Write down new ideas. If any connections come to your 
mind while mapping out the notes, draw another arrow 
and connect. Your notes should be your thoughts, not 
just the lecturer’s.
** Connect ideas backwards. When you hear a new idea that 
relates to an idea earlier in your set of notes, go back and 
link it there. Backlinking is an easy way to create more 
connections in your writing.
** image association

The challenge with hard-to-visualize words is that your 
connection should be more or less unambiguous. If your word 
means “to steal” then you shouldn’t also associate it with “to take”, 
“to share” or “to grab”.
** visceraliztion
Stage One: Paper Pictures
The first stage of any mental technique is on paper. If you 
have difficulty thinking abstractly in your head, write it out.

Once again, talk is cheap, action is what matters. If you want 
to possess savant-like, genius-level visualizing powers you need to 
practice.
* I’d like to argue that your brain is like a search-disabled 
Wikipedia. Tons of information, for sure, but not always the  
clearest route to link it together. However, if you have more links 
between pages in your mind, it is far easier to find the information 
you’re looking for.

* Learn Things Once
 Learning things once is the ideal, but when you start, even 
cutting the number of learning repetitions you normally take in 
half is a huge improvement.

* Interest = Connections
The more connections you make in a course 
to your actual life, the more interesting it will seem.

* Not all Information Was Created Equal
Arbitrary - dates, facts, names with no logical relationship
Opinion - non-factual information (according to so-and-so, 
author of such-and-such...)
Process - information as a skill (coding, designing, etc.)
Concrete - tangible information
Abstract - intangible information (although often with deep 
logical relationships)

* metaphors
Better understanding an idea. Taking something abstract and making it concrete.
Connecting two different fields. Linking science to literature or art to history
Linking within a field. Connecting a complex physics formula to a simpler formula.
Applying ideas. Using metaphors from your life to connect to the subject material
** suggesttions for people wanting to pick up this skill
Forget quality, focus on quantity. People get too self- conscious about their metaphors. Don’t worry if it’s silly 
or stupid, just make sure it’s creative and interesting

Tell stories. Storytelling is rooted in metaphor. If you can 
make a story out of a subject or information, that will create many workable metaphors.

Start small, first. Metaphors can be simple too. You can liken a differential formula to an integration formula

But all the tips in the world can’t make up for practice. The 
more metaphors you make, the easier it will be to make them in the future.
* tips on getting faster at doing things
1. Singletask. If you're multitasking intellectual or creative work, nearly all of the time you're taking more time to do tasks than if they were separate. This is counterintuitive but widely supported.
2. Block out time and set yourself tighter limits. Work expands to fill the time available. If someone put a gun to your head and demanded a task that normally takes 4 hours takes 3, chances are you'd find a way to make it work. Aim to finish work an hour earlier each day. See what happens. 
3. Ask the question: how could this be done in less time. I appreciate you're doing this now on Quora! But *specifically* - with individual tasks. Our brains are wired to answer any question we ask of them (consciously or otherwise) - if you genuinely stop to ask yourself how something can be done with less, your brain might surprise you with an answer. 
I've cherry picked from Tim Ferriss, Anthony Robbins and Stephen Covey here. You could do worse than read up on any of them.
* Getting Started: Implementing Rapid Learning in Your Life
** Set clear goals
However, if I asked them to write down, in one sentence, 
exactly what they want to achieve, most people couldn’t do it. 
They would write several sentences, using lots of fuzzy words 
with nothing specific.
Clarity is important because without being clear, it is too easy 
to get distracted and give up. Unless you can write down a major 
learning goal in one sentence, with precise language, you don’t 
have a clear goal yet.
Take a piece of paper (or open Notepad) and try writing, in 
one sentence, what your goal for learning is.
*** Make the goal learning, not saving time. 
Time saving is a
byproduct of successful learning, not the goal. When you learn 
effectively, you naturally need less time to study. Going at it from 
the other route (study less -> learn more) usually fails.
*** Master techniques first.
 Setting a goal to work on a specific 
technique will be easier to follow than general improvements. For 
your first month, you may want to spend all your time focusing on 
integrating metaphors, or diagrams or visualization into your 
existing studying routine.
*** Start small. 
Focus on one technique to start, and try to focus 
on one course. This doesn’t mean you can’t use the methods 
everywhere, just that if you narrow your focus it will be easier to 
stay disciplined when you don’t feel like doing anything
* Change Your Habits
As I mentioned previously, your 30 Day Trials do not need to 
be directly associated with the learning methods. Setting trials to 
organize your studying schedule, setting daily to-do lists or 
becoming productive are also useful and can help you facilitate 
later practice on rapid learning techniques
* Finally, Practice the Skills
A problem many would-be rapid learners encounter is falling 
back on old studying habits. They understand, intellectually, that 
cramming, rote memorizing and endlessly rereading their notes is 
inefficient. But, when push comes to shove, they fall back on those 
past strategies.
This is because they didn’t adequately practice the skills. 
Driving a car is faster than walking. But if you don’t know how to 
drive, you’re going to walk everywhere out of necessity.
