[[https://www.zhihu.com/question/534902853/answer/2567223501][全局抗衰老]]（内脏/大脑等）：
热量限制，只吃七分饱。小白鼠少吃30%，寿命延长30%。蛋白质，脂肪和碳水中，减掉的应当是碳水。
间歇性断食，又称轻断食。常用方法有，16+8，5+2，隔日轻断食。可激活AMPK抗衰老效应。效果最好，还不花钱。
服用抗衰老补剂，比较重要的是NAD+的前体，比如烟酸/NMN/NR，以及AMPK激活剂，原理同第2条，要花钱，抗衰老效果略逊于第2条。
控制蛋白质摄入总量，长期低蛋白会营养不良，但摄入过量蛋白，会激活mtor引起衰老，高蛋白高碳水无氧力量训练撸铁，激活mtor加速衰老（mtor激活的好处是强化肌肉增长，增强性欲和性功能等，是动物摄入丰富蛋白质营养时的扩张行为，有利于基因延续，但对个体寿命不利，与AMPK是相反的，AMPK是环境营养不足时的休眠行为，会降低性欲和性功能，不利于传播自身基因但能长寿，过度AMPK会引发男士ED和女性月经停止，需连续饱食方可恢复）。
限制碳水总量和快碳，糖化反应加速衰老，并且伤害胰岛。
过量有氧运动加速衰老，每日步数限定在5公里以下。可服用抗氧化补剂，比如VC，槲皮素，姜黄素，花青素等，剂量要把控好。
在西藏高海拔氧气稀薄地区加速衰老，在低海拔海滨城市，衰老更慢。睡在加压有氧舱，衰老更慢。
身材肥胖加速衰老，特别是内脏脂肪高，大肚子。
吸烟，喝酒，嚼槟榔严重折寿，是一类致癌物。长期吸入有毒气体，摄入有毒食物饮品，加速衰老。
熬夜，黑白颠倒，不健康的作息时间，加速衰老。
压力过大，心情不佳，诱发皮质醇激素升高，加速衰老。
选择合理饮食结构，控制蛋白质总量，低碳饮食结构且慢碳水，加上健康优质脂肪，可延缓衰老，例如选择地中海饮食。

颜值抗衰老低碳水低糖生活，防止皮肤糖化反应，防止AGES生成，AGES是皮肤衰老元凶。
每日补充胶原蛋白3000mg，弹性蛋白50mg，保持皮肤营养。
防止紫外线，紫外线是皮肤衰老元凶之一。
每天早晚涂抹各类护肤品人在35岁，60岁和75岁三个节点，会陡然衰老，其中35岁是颜值衰老的关键节点，在35岁的前几年，就要做好颜值抗衰老



每个星期都在做着差不多的事情，那么一年以后你还是一年前的你，只是老了一岁。
人生旅途中，大家都在忙着认识各种人，以为这是在丰富生命。可最有价值的遇见，是在某一瞬间，重遇了自己，那一刻你才会懂：走遍世界，也不过是为了找到一条走回内心的路


少走了弯路，也就错过了风景，无论如何，感谢经历

如果有一天： 你不再寻找爱情，只是去爱；你不再渴望成功，只是去做； 你不再追求成长，只是去修；一切才真正开始

Abandon all your projects so you can be with the flower with no intention of exploiting it or getting something form it.
"When I am with a friend, I want to profit from him or her." Of course we can profit from a friend, but a friend is more than a source of profit. Just to be with a friend, without thinking to ask for his or her support, help or advice, is an art.
It has become a kind of habit to look at things with the intention of getting something. We call it 'pargmatism' and we say that the truth is something that pays. If we meditate in order to get to the truth, it seems we will be well paid. In meditation, we stop, and we look deeply. We stop just to be there, to be with ourselves and with the world. When we are capable of stopping, we begin to see and , if we can see, we understand. Peace and happiness are the fruit of this process. Whe should master the art of stopping in order to really to be with our friend and with the flower.
How can we bring elements of peace to a society that is very
used to making profit? How can our smile be the source of
joy and not just a diplomatic maneuver? When we smile to
ourselves, that smile is not diplomacy; it is the proof that we
are ourselves, that we have full sovereignty over ourselves. Can
we write a poem on stopping, aimlessness, or just being? Can
we paint something about it? Everything we do is an act of
poetry or a painting if we do it with mindfulness. Growing
lettuce is poetry. Walking to the supermarket can be a painting.
When we do not trouble ourselves about whether or not
something is a work of art, if we just act in each moment
with composure and mindfulness, each minute of our life is a
work of art. Even when we are not painting or writing, we are
still creating. We are pregnant with beauty, joy, and peace, and
we are making life more beautiful for many people. Sometimes
it is better not to talk about art by using the word “art.” If we
just act with awareness and integrity, our art will flower, and
we don’t have to talk about it at all. When we know how to
be peace, we find that art is a wonderful way to share our
peacefulness. Artistic expression will take place in one way or
another, but the being is essential. So we must go back to
ourselves, and when we have joy and peace in ourselves, our
creations of art will be quite natural, and they will serve the
world in a positive way.

estern civilization places so much emphasis on the idea of
hope that we sacrifice the present moment. Hope is for the
future. It cannot help us discover joy, peace, or enlightenment
in the present moment. Many religions are based on the notion
of hope, and this teaching about refraining from hope may
create a strong reaction. But the shock can bring about
something important. I do not mean that you should not have
hope, but that hope is not enough. Hope can create an
obstacle for you, and if you dwell in the energy of hope, you
will not bring yourself back entirely into the present moment. If
you re-channel those energies into being aware of what is
going on in the present moment, you will be able to make a
breakthrough and discover joy and peace right in the present
moment, inside of yourself and all around you.
A. J. Muste, the mid-twentieth-century leader of the peace
movement in America who inspired millions of people, said,
“There is no way to peace, peace is the way.” This means that
we can realize peace right in the present moment with our
look, our smile, our words, and our actions. Peace work is not
a means. Each step we make should be peace. Each step we
make should be joy. Each step we make should be happiness.
If we are determined, we can do it. We don’t need the future.
We can smile and relax. Everything we want is right here in
the present moment.


People were quite happy to learn about the various forms of self-serving bias and then apply their newfound knowledge to predict others' reponses. But their self-ratings were unaffected.
Even you grab people by the lapels, shake them, and say, "listen to me! most people have an inflated view of themselves. be realistic" they refuse, muttering to themselves, "Well, other people may be biased, but I really am above average on leadership"

We further believe that the facts as we see them are there for all to see, therefore others should agree with us. If they don't agree, it follows either that they have not yet been exposed to the relevant facts or else that they are blinded by their interests and ideologies. People acknowledge that their backgrounds have shaped their views, but such experiences are invariably deepening one's insights; for example, being a doctor gives a preson special insight into the problems of the health-care industry. But the background o fother people is used to explain their biases and covert motivations.
看人长处、帮人难处、记人好处


有很多事情，自己其实明明知道真相。却忍不住拼命找到漏洞和借口来推翻真相，成全自己
心里想要的答案

不说硬话、不做软事。菩萨心肠，霹雳手段。别人触犯你原则时，面带微笑地硬刚到底

不要想着取悦所有人，再好看的电影都有人喷粪。在认同中找快感，在反对中找视野

花钱才能致富，省钱只会脱贫

不要被假日的概念误导。不要认为假期就是不用工作，散漫。要做不平凡的成绩，就不能有大众一样的想法。

如果喜欢一件事，就放开手脚去喜欢。比如很多人对钢管舞有偏见，其实不是大家认为的那样

观察学习身边人优秀的细节，拿到为自己所用。

不用强迫自己合群

不要玻璃心，不要随便给自己加戏。

警惕一段来得太快的关系。看起来美好的东西，往往藏着你看不到的残忍

任务成长，都是逆着人性来的。太顺利的环境，无成长

人一到群体中，智商就严重下降。为了获得认同，个体愿意抛弃是非，去换取那份让人备感安全的归属感

别在别人身上找安慰

这世界上没有什么是不能失去的。

坚持写复盘日记，反思今天的收获和不足

安分工作，老实生活，这只是你过好生活的基础；勤于思考，找不对称，才有出路

不要考验人性

人生只有两件事能报复你：努力不够的悔恨和糟蹋身体的后患

不要浪费你本就稀少的宝贵时间在没有意义的人和事情上。

你一生中大部分的精力，应该只放在一件事情上。把这一件事情做到极致，胜过你把一万件事做得平庸

* 思维方式
1.凡是我的想法和大多数人一样，就肯定不行，不一定是错的，但一定是没什么价值的。我一定要想办法寻找到一点点与众不同的东西。写作文就特别需要这种思维，但实际上，做数学题也需要，面试和工作也需要，挣钱和创业、消费与投资也需要，甚至婚姻、家庭和教育孩子还会需要。
2.如果我找不到与众不同的想法，就必须去关注反对的声音，却了解一下反对的立场，看看自己是不是处于一个庸俗无聊的低端而不自知。如果是，完全可以放弃自己的想法，重新来过。如果不是，至少可以从反对者哪里获得一点新东西，比如，你至少能够理解他们为什么如此着急上火反对你的原因，因此你可能变得更大度一些。
3.如果连反对者都没有，或者很少，那么，请一定要去找老师了。哪怕你已经取得很大成功，能掌控很大的事，你也可能处于危险之中。

詹姆斯关于情绪的观点在当时也很新颖。传统观点认为，我们看到一只熊，感到害怕，然后逃跑。詹姆斯却认为，我们看到熊，身体试图逃跑，这才感到害怕。
每当感到害怕时，我就吹口哨，吹出快乐的情绪，一会我就不害怕了。”詹姆斯说。他的实验，你可以找个机会来试一把，我肯定有效果。不会吹口哨的，可以唱歌，吃东西，或者只是洗把脸，放松一下，实在不行，你就洗个澡，或者给你家的宠物洗个澡

* meaning less of life
What is the basic structure of you? What are “you” made of?

Beliefs mostly.

Your beliefs form a tapestry of narrative over time that creates the grand illusion of you. But have you ever stopped to ask where your beliefs and ideas really come from?

Once you start to dig into them and tear them apart, you realize what a flimsy and rotten foundation most of them are built on.

we are literally children wearing adult costume bodies
We live in a society of, by, and for children.

Nobody ever taught you to think for yourself, or reflect on your beliefs, or asked you how you came to believe what you believe, or how you got to be the way you are, because everyone around you is a child too, filled to the brim of their operating capacity with childish beliefs.


Your beliefs are not your own and they never were.

That’s the bad news.

The good news is you can do something about it.

As Hemingway said “the fastest way to do something is to actually do the thing.”


You can start making real choices instead of living life like a non-self aware program that has all its decisions pre-programmed in by its inherited beliefs. You don’t want to be an NPC, a Non Player Character, with a limited range of stimulus and response. You want to be the protagonist in the story.

Then the real fun begins.

What will you do with your new self?

Do you want to take off and explore the world? Do you want to paint? Climb mountains? Drive race cars? Become famous? Become anonymous? Do you want to change the world? Do you want a simple family life, where you actually choose a partner you find amazing, instead of a relationship you just stumbled into because he/she/they were close by when you reached mating age?

You can decide to be Space Beth and take down the intergalactic government or you can decide to be Earth Beth and stay at home or anything else you can possibly imagine. You can choose to be a saint or sinner or a sage or priest or a celebrity or a simple baker of cupcakes with smiley faces on them.

The only question that matters is this:

What choice will you make?

我把自己想象成80岁的模样，并思考：“现在回望我的一生，我要把遗憾事件的数量降到最低。”我知道在我80岁时，我不会因这次尝试而后悔，我不会后悔参与到互联网这个我认定是了不起的事情中来。我知道，哪怕我失败了，我也不会遗憾，而我可能会因为没有尝试而最终后悔不已。如果你能想象自己年满八旬，并思考“老了的我会怎么想呢？”这个问题，你就可以因此而摆脱每日琐碎的困惑的干扰。你要知道，当时我从那家华尔街公司离职创业时恰逢年中，这样连年终分红都没我的份了。就是这类短期的事情会干扰你的判断，只要你把眼光放得更长远些，你就可以做好生命中的重大决定，而不至于日后后悔了。


“When I was 17, I read a quote that went something like: 'If you live each day as if it was your last, someday you'll most certainly be right.' It made an impression on me, and since then, for the past 33 years, I have looked in the mirror every morning and asked myself: 'If today were the last day of my life, would I want to do what I am about to do today?' And whenever the answer has been 'No' for too many days in a row, I know I need to change something.”



肝好的人容易酗酒致死
游泳好的人容易溺亡
聪明的人过于依赖自己的聪明，而忽略了对于自身不足的探索
尊重他人，内化到日常行为点滴

从画画角度看问题，从视觉看问题，文字其次
美就在身边，只是你的眼睛忽视了它~ ^ ^ 这是真的哦
强化
其实这个原理大家都懂，但是随着年龄的增长，越来越不会赞美别人。在强化的使用中包括正负两种。正强化就是常规所提到的一个人做对了一件事情要及时进行表扬，负强化则是指去除一个对他不利的因素。
这里还要提到的是惩罚，负惩罚就是常规提到的给与其不喜欢的因素，但是在教育或者日常生活中，要想达到惩罚目的，更舒缓的方法是负惩罚，即去除他喜欢的因素

太阳底下无新鲜事
天下人熙熙攘攘，皆为利。人的本性古今无异。贪嗔痴如影随形。
世道轮回千万遭，都逃不出爱恨情仇，利益纠葛。所有故事都不过是换汤不换药的重复。不同时间，不同空间，不同面具，同一群人。
事实上，我们不仅是微尘，我们还是夏虫，是蜉蝣。

你的现时遭遇，往往是自己以往的重复，也是别人的重复。
科学技术扩展了对外的视野，然而离自己的内心越来越远。
我们已经不认识自己了，在商业资本的洗脑冲击下，在社交媒体的轰炸中，大脑无时无刻不在接受处理各种导向性信息。
人更像是生物机器人，被动接收指令，步伐动作一致地奔赴。

人类的祖先很可能不是生理条件上最具有优势的支系，有一种类人猿，他们比我们的人类祖先有更多的先天优势，比如有很结实的牙齿足以去消化一些纤维很粗的球状植物，所以他们可以不用去到处进行一些危险的觅食活动，满足于一直靠啃食球状食物为生，后来地球上的环境变化了，球状植物大量减少，所以最后这种类人猿物种由于找不到充足的食物而逐渐消失。这就是人的祖先具有antifragile的特性啊
	他们的消亡不是因为失败太多，而是因为尝试太少

也就那样
等我渐渐长大之后，我发现原来出国、读名校、念博士、买房、泡美女、进大企业等等事情，就像钱钟书先生所谓的“出水痘”一样，出过之后就产生了免疫力，之后便不再惦念了。这个过程其实是破除迷信的过程，你会发现，原来向往乃至崇拜的价值，其实也不值一提。自信若建立在这些水痘上，真就成了自卑了。
感觉还是好多人对这段话的理解有偏差。这段话没让你不去追求这些东西，这些东西都是好的，你可以去追求，但是别太执着于这些东西，更不要因为实现了其中一样活着几样就洋洋得意，就想以此来证明自己的牛逼。这些东西都是好的，但它们只是你人生路上的风景，最多算个指示牌，绝对不是什么目的地，更不是你证明自己的凭证。

20220109
一个人的突破需要外力刺激。一个社会的变化发展，也是需要外力的干涉。
25号实验中的老鼠，去除了一切外部压力下的生存状况结果足以证明无忧无虑的可怕
大清王朝如果没有资本主义国家的侵略，会是什么样子

人类并不拥有想象力，有的只是模仿和再组合的能力

 Don't treat yourself like a child. Always be professional.
