* Easily distracted: why it's hard to focus, and what to do about it
impact: how to manage distractions.

If you are paid to answer emails or deal with customers all day then this post might not be for you. But if you're someone who often needs to get some thinking done, read on...

An epidemic of overwhelm
People everywhere seem to be experiencing an epidemic of overwhelm at work. I believe it's a function of two things. Firstly it's the amount of information we now process, which our brain may not be used to.  I read somewhere that The New York Times on Sunday contains more information than the average 18th century French Nobleman learned in his lifetime (now, if only I could remember where I read that...)

Secondly, we have all these new technologies which are very good at distracting us, which our human habits have not caught up to. The challenge is that we have not realized the true cost of distractions: they use up what is actually a limited supply of attention each day, and make us far less effective if we need to do deeper thinking work. For example, a university of London study found that being always connected impacts your IQ equivalent to losing a night's sleep or taking up marijuana.

Attention is a limited resource
Every time you focus your attention you use a measurable amount of glucose and other metablic resources. Studies show that each task you do tends to make you less effective at the next task, and this is especially true for high-energy tasks like self control or decision making. So distractions really take their toll.

Here's more on this from the book:

Distractions are everywhere. And with the always-on technologies of today, they take a heavy toll on productivity. One study found that office distractions eat an average 2.1 hours a day. Another study, published in October 2005, found that employees spent an average of 11 minutes on a project before being distracted. After an interruption it takes them 25 minutes to return to the original task, if they do at all. People switch activities every three minutes, either making a call, speaking with someone in their cubicle, or working on a document.

Distractions are not just frustrating; they can be exhausting. By the time you get back to where you were, your ability to stay focused goes down even further as you have even less glucose available now. Change focus ten times an hour (one study showed people in offices did so as much as 20 times an hour), and your productive thinking time is only a fraction of what's possible. Less energy equals less capacity to understand, decide, recall, memorize, and inhibit. The result could be mistakes on important tasks. Or distractions can cause you to forget good ideas and lose valuable insights. Having a great idea and not being able to remember it can be frustrating, like an itch you can't scratch, yet another distraction to manage.

Remove temptation
So how can we address this? 
The answer is quite simple. Once you understand how much energy is involved in high-level thinking like planning and creating, you might be more vigilant about allowing distractions to steal your attention. One of the most effective distraction-management techniques is switch off all communication devices during any thinking work. Your brain prefers to focus on things right in front of you. It's less effort. If you are trying to focus on a subtle mental thread, allowing yourself to be distracted is like stopping pain and enjoying a mild pleasure: it's too hard to resist! Blocking out external distractions altogether, especially if you get a lot of them, seems to be one of the best strategies for improving mental performance. There is no 'trick' to this: you simply must switch things off, or you wont focus.

So part of the solution to managing distractions is quite easy in theory, it just takes some courage. It's also not negotiable: there's no way not to be distracted by distractions, it's built into the brain in the way we pay attention to novelty.

Distractions are not just external though. Here's more from Your Brain at Work:

Awash with activity
As adolescence hits and you become more conscious of an inner life, many people notice that their mind is hard to control. Strange thoughts pop into awareness at odd moments. The mind likes to wander, like a young puppy sniffing around here and there. As frustrating as this tendency can be, it's normal and it tends to stay this way through life. One reason for your wandering attention is that the nervous system is constantly processing, reconfiguring, and reconnecting the trillions of connections in your brain each moment. The term for this is "ambient neural activity". If you were to look at the electrical activity even in a resting brain, it would look like planet earth from space with electrical storms lighting up different regions several times a second.

Trey Hedden and John Gabrieli, two neuroscientists from MIT, studied what happens in the brain when people are distracted by internal thoughts when doing difficult tasks. They found that lapses in attention impair performance, independent of what the task is, and that these lapses in attention involve activating the medial prefrontal cortex. The medial prefrontal cortex is located within the prefrontal cortex itself, around the middle of your forehead. It activates when you think about yourself and other people. This region of the brain is also part of what is called the "default" network. This network becomes active when you are not doing much at all, such as being in between activities while in a scanner. Hedden and Gabrieli found that when you lose external focus, this default brain network activates and your attention goes to more internal signals, such as being more aware of something that may be bothering you.

Driving away from distractions
You might wonder how you ever stay focused. We have specific neural circuitry for this process, though it doesn't work the way you might expect. A key part of maintaining good focus occurs based on how well you inhibit the wrong things from coming into focus.

A common test that neuroscientists use to study the act of focusing is the "stroop" test. Volunteers are given words printed in different colors, and told to read out the color of the text, not the word itself. In the example below, the brain has a strong desire to answer "Grey" for option c., as it's easier for the brain to read a word than to identify a color.

a. Black
b. Grey
c. Grey
d. Black

To not read the word "Grey" requires inhibition of an automatic response. Using scanning technologies neuroscientists have observed people inhibiting their natural responses, and discovered the brain networks that are activated when this happens. There is one specific region within the prefrontal cortex that keeps showing up as being central for all types of inhibition. It's called the right and left ventrolateral prefrontal cortex (VLPFC), and it sits just behind the right and left temple.

The VLPFC inhibits many types of responses. When you inhibit a motor response, a cognitive response or an emotional response, this region becomes active. It appears that the brain has many different ‘accelerators', with different parts of the brain involved in language, emotions, movement, and memories. Yet there is only one central braking system used for all types of braking.

Your ability to use this braking system well, the VLPFC, seems to correlate closely to how well you can focus. It seems that to focus we need to learn to stop ourselves from going down the wrong path. One of the challenges with this process though is that this braking system isn't very effective.

Putting on the breaks
If you were a car company and were building a new type of on-road vehicle you would make sure the braking system was made out of the most robust materials possible, because brake failure is not a happy thing. Well in the case of human brains, the opposite has happened. Our braking system is part of the most fragile, temperamental and energy-hungry region of the brain, the prefrontal cortex. Because of this, your braking system only works at its best every now and then. If cars were built like this you'd never survive your first drive down to the store. All this makes sense when you consider it: stopping yourself from acting on an urge is something you can do sometimes, but is often not that easy. Not thinking about an annoying, intrusive thought at times can be very difficult. And staying focused, well sometimes that appears downright impossible.

Timing is of the essence
So, inhibiting distractions is a core skill for staying focused. To inhibit distractions, you need to be aware of your internal mental process and catch the wrong impulses before they take hold. It turns out that, like the old saying goes, timing is everything. Once you take an action, an energetic loop commences that makes it harder to stop that action. Many activities have built-in rewards, in the form of increased arousal that holds your attention. Once you open your email program and see the messages from people you know, it's so much harder to stop yourself from reading them. Most motor or mental acts also generate their own momentum. Decide to get out of your chair and the relevant brain regions, as well as dozens of muscles, are all activated. Blood starts pumping and energy moves around. To stop getting out of your chair once you start will take more focus and effort than to decide not to get up when you first have the urge. To avoid distractions it's helpful to get into the habit of stopping the wrong behaviors early, quickly, and often, well before they take over.

And here's a big take away from all this. Manage what you focus on. Pay attention to your attention, and stop yourself from getting on the wrong train of thought early, before it takes over. This is the oppositive of being mindless: it's being mindful.

The best way to do that is to practice being aware of your own thoughts, by activating your observer function. How do you do that, when you have a ton of information pouring through your head as you process a hundred emails in the morning? The answer is clear: you can't. If you want to do deeper thinking work, don't start your day overwhelming and exhausting your brain. Start with the tougher work that requires a more focused, quiet mind. Many people have this back to front. If your job is to think, tackle thinking tasks early, and tasks that are relatively 'interesting' such as checking your emails (which means your brain will go there easily) later when you are tired.

So in summary, how do you beat back distractions? Turn everything off. And do your deeper thinking work in the morning while you still have the ability to control your attention. Sounds easy enough. In practice it's tough, but it works.
* The Most Important Communication Skill You Will Ever Need
Everyone’s experienced those awkward social moments when there’s an overly long
pause in the conversation or you’ve inadvertently interrupted the other person.
These social gaffes can occur in face-to-face interactions, but are far more
likely to happen when you’re on the phone with your conversation partner because
you can’t read nonverbal signals of facial expression or body language. Even
video chats can be punctuated with uncomfortable silences and the feeling that
you’ve spoken too soon, again because you’re not able to take advantage of the
cues you would get by being in the room with the other person.

According to University of Groningen’s Namkje Koudenberg and colleagues (2017), these conversational hiccups, all too common, can have serious life consequences. They cite the example of a video call interview with a job applicant. The applicant may get all the questions “right,” but still not get the job because of lack of conversational flow so that you don’t feel you’ve clicked: “She seems a bit distant or aloof and does not seem very enthusiastic as it takes her some time to respond—or laugh about your jokes” (p. 50). As the authors point out, conversational flow, that sense of clicking with the other person, is essential to developing “a close social connection” (p. 50).

Through the process of “grounding,” the Dutch researchers note that we establish a shared reality with the people in our social world. This process involves validating shared viewpoints which promotes a sense of identification between conversational partners. They use the term “solidarity” to refer to the emerging sense of “we-ness” that a conversation marked by flow can help establish. Clearly, you’d be more likely to hire a job applicant or go out on a date with someone when you find the conversation to be easy and natural. You’ll reject a prospective applicant or social partner if you don’t feel connected because something about the conversation seems off.

In their review of the communication literature within social psychology, Koudenberg and her collaborators explore the factors that promote conversational flow. By extension, if you take advantage of some of these strategies, your interactions should help you in the grounding process with the people who are important to you.

Let’s begin with the nonverbal components of communication. You can help bond with your conversation partners through such processes as nodding, smiling, and leaning forward, particularly if you take care to mimic the nonverbal behaviors of your conversation partner. In your verbal communication,  if you accommodate to the way in which the other person speaks, you can similarly promote the bonding process. At perhaps the most basic level, if you start to speak in the same dialect as the other individual, you reveal that the two of you share a similar social group and hence, world view. Perhaps this explains why non-Southerner politicians sometimes fake a drawl if they're trying to win the crowd's liking, and their votes.

Your body participates in the we-ness formation process as well, according to Koudenberg et al. “Behavioral matching” occurs when you adopt the posture of the person to whom you’re speaking. Even more cementing between yourself and the other person occurs if those mirroring moments happen to occur at the same precise moment in time.  As they note, “dyads walking down a lane tend to synchronize their steps, and football fans often chant simultaneously.” Getting in sync with the other person’s movements can lead to “blurring of psychological boundaries” (p. 54). You might also work in complementary fashion with the other person, such as joining efforts in lifting a heavy piece of furniture that needs to be moved. As you and the other person heave-ho together, you feel an emotional as well as physical sense of coordination.

Taking turns in conversation is the next area that the Groningen researchers investigated. As I noted earlier, both interruptions and long pauses take their toll on your sense of connection with conversation partners. Finding that rhythm with the other individual’s stops and starts is similar to the physical synchronization patterns shown in your body language or actual movements. Even though you may be advised to avoid saying “um” and “yeah” in a formal conversation, such interjections can help, Koudenberg argues, to regulate the pace and timing of flow. Indeed, they maintain that flow is one of the most important ways to establish mutual trust and perceived mutual understanding. In a group setting, the same principles hold true. If you’ve ever been in a room with someone who seems to walk all over the other group members during a mutual conversation (and who hasn’t?), you know how disruptive this lack of flow can be to a sense of shared purpose.

Why should conversation flow be so important to promoting feelings of mutuality? One possibility, the Dutch team point out, is that it builds positive feelings between group members, who like each other better when they feel they are communicating on the same wave lengths: “a fluent exchange with another person may be a positive experience because it is so effortless” (p. 58). These interpersonal relationships add up to stronger feeling of connection to the group as a whole.

Conversational flow affects group identity, further, by regulating social norms within the group. Hugging, kissing, or a simple nod of recognition: which do your various social groups use as forms of greeting? If you’re a hugger and this group is not, you’ll soon learn to refrain from what seems like an overly familiar type of greeting. Using an obscenity in a group that condemns any swearing will also be perceived as deviant and could lead you to be excluded although you’d quickly realize you need to clean up your act if you want to be part of this particular crowd.

Gestures, word choice, and other elements of communication also signal the status hierarchy within the group. If you’re a new member of a group, or of lower status than everyone else, you will be less likely to interrupt other people than if you’re at the top of the power structure.

The longer a group has been together, though, the more flow interruptions they can afford to make without threatening either the individuals in the group or the group’s identity. When you’re enjoying lunch with your oldest friends, you’ll be less likely to fuss if someone interrupts you than if you’re cut in on by your sister’s new boyfriend. You and your friends will also be better able to regulate your conversational flow, but violations won’t be disruptive to the solidity of your feelings toward you have each other unless they happen repeatedly and deliberately, in which case the group may actually be in the early stages of dissolution.

In conclusion, the kind of “micro-characteristics” of dialogue (p. 63) that promote flow can influence everything from feelings that people in a conversation have about each other to the overall sense of identity within a larger group. The subtle signals that you send and receive over the course of your interactions have far larger consequences than you realize. Fulfillment in relationships depends on many factors, not the least of which are these small but impactful interpersonal cues
