* Life Advice: How do you simplify your life?
Remove ALL Apps from your phone. You are not even using the Productivity Apps or
the Notes on your phone. Throw out everything. Period. Use your phone for
calling and messaging people that is all. Get away from your phone as much as
possible. It is a tool, not your best friend.

Clean your space. There is no reason to have a messy home. All it does is it
makes you sulk even more. Keep a clean home, a clean working area and you will
simplify your day a lot.

Clean your self. Be proud, happy and excited when you walk out of the door in
the morning. But even if you do not go outside, still keep yourself in top
shape. Not for anyone else but for yourself.

Eat more greens. There is enough going on in your life that you shouldn’t have
to worry about your health, your body and your fitness as well. Keep it as
simple as you can and help yourself as much as possible.

Drink more water. Your brain needs all the Oxygen it can get. Drinking more
water increases the transmission of Oxygen to your brain, which makes it a lot
simpler to think faster.

Do what can be done in 2 minutes right away. Get the small stuff out of the way
right away. Do not wait until it gets so big and important that you have to do
it and that it creates stress.

Complete organizational tasks right away. All that government stuff and all the
work-related stuff you do not want to do. Get that done right away. You do not
want to do it, but you know you have to eventually, so you might as well do it
as soon as you receive the task.

Check your messages 1–2 times a day, not more. Unless it is your job do not
check your messages more often. And, if you really want to simplify your life a
lot, then you pick a time at which to message people, even your friends. Make
working easy by even ignoring IMs and Calls until the time you chose.

Get up early. Even if you are a person that works better at night, if you wake
up early you will get more stuff done. It is theoretically impossible that all
successful people are morning people, yet they are. That means that there must
be a reason to wake up earlier than to stay up later. Copy the ones that are
doing it right.

Go to bed early. To make it easier for you to get up, to avoid the random
parties you regret going to, and to stop yourself from drug and alcohol abuse,
do yourself a favor and go to bed early. Going to bed at 10 p.m. means you can
get up at 5 a.m. and start your day before the sun even gets up.

Start over on your email. Create a New Email Address. Do not even bother
unsubscribing to everyone. Just get a new email address and start giving it out
to the most important people. You will have to check 2 Email Adresses for a
while, but soon you will have one with ALL the important stuff in one place, and
another Email to give to all the unimportant newsletters.

Stop drinking alcohol or smoking. Completely stop. No ifs, ands or buts.

Throw out your TV. Do it to fight all the negativity. All the bad news, all the
commercials telling you you are not good enough and all the Drama TV Shows. Just
throw it out entirely.

Go outside. Take a walk outside. Even if it is just for 10 minutes a day. Get
out of any stressful environment. We all know the feeling of having a lot of
Tension in the room, well the same thing happens when you work a lot and leave a
bad mood. Get away from that environment and go outside to recharge completely.

Smile. Leave a better environment in your wake by smiling more often. Smiling
releases the feel-good-hormones Serotonin and Dopamine. Having a better mood is
always simpler and easier than walking around depressed or angry.

Listen to uplifting music. Get into an even better mood by listening to all the
amazing Music. Listen to it as often as you possibly can and really get invested
in it. Create a better mood, remove all the stress from feeling negative and
have more fun.

Be Honest. Be brutally honest with everyone, especially yourself. Tell people
what you really think and tell yourself what you really need to do. This will
bring a new change in your life that ends with having a much simpler Life.

Remove unnecessary friends. This is probably the single best tip to simplify
your life. Anyone that is not making you feel better, is not empowering you and
does not want you to be your absolute best should not be worth your time.
Basically, if you can think about removing them from your life, then do it.

Say No. Say No to all the Bullshit things you do. Say No to watching TV, playing
video games, eating candy, eating chips, drinking alcohol and all of the other
bad things to do. Really say it out loud to remove it from your life.

Say Yes. But say Yes to all the amazing things as well. Say Yes to working hard,
to enjoying Life, to going out with your friends, to falling in love, to working
out, to eating healthy, to drinking water, to goofing around and to all the
other incredible things in your life. Say it out loud! “YES! I will live an
amazing Life!”.

* How do you convince your mind that it's okay to fail?
F**k it.

Just f**k it.

I asked for a girl’s number at a club once. She just shook her head at me. Whatever. F**k it. I walked away. I’ll get to know other girls.

My first ever girlfriend didn’t allow me to have sex with her because of God and shit. She manipulated me to break up with her so she could be with her ex, and
they were sleeping together. Whatever. F**k it. I’ve had better relationships after her.

I nearly flunked out of college after my first semester. The dean made me go see him and shit. Whatever. F**k it. Studied harder after that and doubled my GPA.
Graduated eventually. Didn’t give a fuck about other kids who kept comparing grades and based their self-esteem on it.

Dad died when I was only 20. Whatever. F**k it. Moved on eventually.

I struggle with my business. Whatever. F**k it. I am learning and I am proud of my art.

I make less money than my peers. Whatever. F**k it. I don’t spend on needless shit like they do.

Wrote some articles. Nobody read or shared it. Whatever. F**k it. Continued to write.

The girl I thought I’d marry disappeared on me at the end. Whatever. F**k it. I don’t need to deal with toxic people who don’t want to act like adults.

Not even sure if anyone would give a shit about this answer. Whatever. F**k it.

It’s not about trying to convince your mind or whatever.

Things go wrong all the time. Nobody is perfect. We’re all just playing along and trying to figure it out along the way. This is a fact, but others would try to tell you otherwise.

Just live. Do your shit. Do your work. You’re not an idiot. You learn shit. Just keep on keeping on and stop overthinking the shit out of everything. That’s pointless.

If at this point you feel like you’ve a ton of questions and you’re like, “But, but, but…”

Whatever, just, whatever, okay?

F**k it.

It will be okay.
* What are the lessons people most often learn too late in life?
1) Time passes much more quickly than you realize.
2) If you don't take care of your body early then it won't take care of you later. Your world becomes smaller each day as you lose mobility, continence and sight 
3) Sex and beauty fades, but intimacy and friendship grows
4) People are far more important than any other thing in your life. No hobby, interest, book, or work is going to be as important to you as the people you spend time with as you get older. 
5) Money talks. It says "Goodbye". If you didn't plan financially for your old age when you are young you will wish you had. 
6) Any seeds you planted in the past, either good or bad, will begin to bear fruit and affect the quality of your life as you get older for the better or the worse
7) Jealousy is a wasted emotion. People you hate are going to succeed; people you like are going to sometimes do better than you did. Kids are going to be smarter and quicker than you are. Accept it with grace.
8) That big house you had to have becomes a bigger and bigger burden even as the mortgage gets smaller. The cleaning, the maintenance, the stairs, all of it... becomes less attractive every day. Your possessions own YOU. 
9)  You will badly regret the things you DIDN'T do far more than the things you did that were "wrong" -- the girl you didn't kiss; the trip you didn't take; the project you kept putting off; the time you could have helped someone. If you get the chance - do it. You may never get the chance again.
10) Every day you wake up is a victory.
Bonus: It's never too late to become what you wanted to be or might have been if you START RIGHT NOW!
11) What people think of you is none of your business. Ignore them, whether it is good or bad, and keep your eyes on your goals. The biggest liar in the world is "They say...".
* What is the best thing you have ever heard a teacher say?
My high school physics teacher started his course as follows:
“If any of you came here expecting me to teach you anything, you might as well leave. Those of you who came here to learn should stay.”
This was the first time I clearly understood my education as being self-directed, rather than response to parental and teacher demands.
* What are the secrets of being likable?
When I was young I thought the secret to popularity was to be as impressive as possible so people would want to talk to me.

Instead they thought I was arrogant.

Then I examined what made me want to befriend someone, and I learned that I'd had it all backwards. The real secret to popularity is not to be impressive, but to be impressed.

I spend an entire conversation asking questions, saying "wow" and "that's so interesting" and "you know so much about this do you mind telling me more?" 

I barely need to say a word about myself or my knowledge. Now people call me "down-to-earth"; they want to be my friend, even if the only thing they know about me is that I make them feel validated. 

Everybody - from ages 1 to 100 - wants to be impressive. So let them be, and they will gravitate towards you. 
