 "What's the worst that could happen?" -- is all you need to learn to do anything.

* <strong>运用道理到实践中往往是另外一会事,是最重要的事</strong>
* A) QUIT YOUR JOB
I'm 48. Here's what a man should know.
You can't get rich at a job. You have to get rich by either starting a business or having multiple streams of income.
Don't quit your job tomorrow. Be a man. Be responsible. Just do it over time but every day move towards this goal.
Why do you need to get rich? Is this particular to a man?
Not really. Woman should do this also. But historically, men in our society have been the bread earners and you will feel better about yourself if you can do it.
So do it.

* B) DON¡¯T LET SOMEONE ELSE VALIDATE YOU
If you want to make a TV show, make a video. If you want to write a book, write it and self-publish.
If you want to be an investment banker, find one company that wants to get sold and another company that wants to buy it and put yourself in the middle. You don't need to be "chosen" by Goldman Sachs.
If you want an education, find a way to learn online. You don't need to get a degree in X to be X (unless legally).

* C) HEALTH.

Men die earlier than women.

There's really only three keys to better health. I'll add a fourth.

Sleep well. Eat well. Low stress. And to help all of the above go faster, exercise.

Fill in the blanks how you want to get the above done. It doesn't matter. As long as you are aware of how important the above four towards living to be 100 with high quality of life then you will do it.

* D) DON¡¯T OUTSOURCE YOUR SELF ESTEEM

Sometimes I've met a woman and I've basically given her all of my self-esteem to take care of.

Then she gets tired of me, bored of me, and dumps me, and now she's taken my self-esteem away until i find it again.

It's hard enough for any one person to manage their own self-esteem, let alone yours.

Take care of your own self-esteem.

* E) CREATIVITY

When you are creative, you become competent. Every day try to do one creative thing a day that makes you feel good.

This is one way to make yourself your priority and never anyone else.

Does this seem selfish? It totally is.

But 1% a day improvement in creativity compounds you into a giant among people.

You will feel good, you will have better relationships with people, you will be able to do what you want.

Oh, there¡¯s one more and it¡¯s basically obvious. Always be honest. See? Obvious.

Do I do these things? I can tell you that when I haven't my life has fallen apart. And when I have, I can do whatever I want.

* 1. Make Small Decisions Rather than Large Ones
Make smaller decisions. Rather than these big monumental decisions, you can look to make small, incremental decisions that can be changed or fixed. You are less likely to attach your ego onto such things.

* 比较是痛苦的源泉,你有财富是错误的说法,它在这个世界上属于你只有几十年,还要你为它劳心伤神. 心不为形役,自然获全.现在人普遍焦虑的,为已有的或者没有的担心,其实那些从本质说是没有意义的.
只是进化来的一种提醒防御机制.知道了预防理智的忽略就好.无能为力的也忽略,因为无法控制
* If it doesn’t challenge you, it doesn’t change you
