* 与神对话
作者：旅行者一号
链接：https://www.zhihu.com/question/47271970/answer/3137089802

作者问自己的生活什么时候才能平步青云？神给出了详细的回答。
首先，你要仔细想清楚，你想要的那种美好生活是什么样的，
在那样的生活中，你要成为什么样的人，做什么样的事，拥有什么样的东西，
你要经常琢磨这些事情，直到你能想的非常清楚，然后重点来了，
想清楚以后别的什么都不要想，不要想但是如何如何，我还不够如何如何，
所有负面的，消极的想法都不要想，把它们都排除在你的思维之外，这个需要训练，
此时作者质疑到，说的到是容易，实际上很难做到吧？
神说，这事不难，只是需要练习。练习的方法神也给出来了，
首先，监视你的思维活动，去思考你正在思考的事情，这个就是李笑来说的元认知，
对于认知的认知，能够审视自己的思维活动，当你发现自己正在负面思考，你就换一种思维，这就是练习的过程，
可能你会说，扯淡，思维是说换就换的吗？以前我也觉得换不了，最近两年，我渐渐发现这其实是自由的，
我脑子里有积极的思维，消极的思维，他们都很多，而我可以选择，
这一点马斯克在一个采访中也提过，他年轻的时候会抑郁，后来发现人是有一种自由的，选择怎么想的自由，
意外受伤截肢的人经过一段时间的练习，能够学会用另一只手做事，甚至用脚来做事，原因无他，因为大脑的可塑性强，
所以我觉得与神对话中说的练习是可行的，你也可以继续对此质疑，继续不相信这些，
因为最后神说了，如果你需要复习，我们可以用几辈子的时间。我觉得上面那段神给的建议说的很对，
绝大多数人都是不想要什么特别清楚，但你问他想要什么经常都是含含糊糊，这正是问题所在，
如果思维真的可以创造我们的生活，那你如何指望用含糊不清的思维来创造想要的生活呢？
我觉得与神对话最大的作用是提供了一个完全不同的视角，
作者说，他以为神是比较严肃的，神说：别这样定义我，也别这样定义自己。
我觉得这是很重要的话，人们学会了语言之后就开始各种定义和评判，生活中大量的矛盾，冲突，痛苦都源于这种定义和评判。
你看整个互联网，贴标签的行为满天飞。这样并不利于人们了解真相，只能增加误会。
还有，作者提到做为父亲，他有义务为孩子提供良好的物质保障，大多数人都会觉得这理所当然，
神说的却是另一种思维方式，你的职责是让他们学会独立；尽可能迅速和彻底地教会他们如何在没有你的情况下生活。
因为只要他们需要你才能活下去，你对他们的宠爱便是假的；唯有当他们意识到你是多余的时候，你对他们的宠爱才是真的。
我觉得这非常有道理，很多老年人在照顾孙辈时都会犯这样的错误，他们喜欢无微不至，把孩子照顾的生活不能自理，
这看起来是爱，真的是么？其实连豺狼虎豹都懂，小崽长大一些，妈妈就一定会让孩子自己尝试捕猎，
起码也用一些容易上手的猎物做练习，而不是天天精心给小崽准备三餐，动物都知道，不能及时独立，
意味着更低的生存概率，不确定性随时可能出现，也许一次失败的捕猎，母狮可能被猎物反击，刺伤了大腿，可能在荒野中伤口很快感染，母狮就丧失了捕猎和哺育幼崽的能力，所以必须尽快让小狮子独立，人当然有很多补救措施，但依然有小概率的意外事件，你天天用你所谓的爱把孩子照顾的生活不能自理，万一你遇到小概率事件，突然离开，孩子的生活怎么办？记得看过日本一个纪录片，里面的妈妈身患重病，时日不多，她一直在教年幼的孩子如何煮饭做菜，收拾家务，打扫房间，洗衣服干活，因为她知道，不久后孩子就会失去妈妈的照料，她必须在此之前教会孩子独立，普通人虽然并不清楚自己能活多久，但早一天教会孩子独立生活依然是正确的选择，你不知道明天和意外哪个先来。还有，关于金钱，书中提到诱发思维这个概念，并给出了解决方法，正常人的创造过程是：思维，话语，行动，而神给的解决方法是反过来，你必须先依照你希望成为的样子去行动，行动多了，从中获得新的经验，然后促使你说出新的话语，新的话语说多了，你就会改变自己的根基思维或者叫诱发思维，作者质疑到，那不就是洗脑吗？神说，你以为你现在脑子里装着的各种思维是哪来的？它们绝大多数都是外界灌输的，你很少根据自身的经验去思考，既然都是灌输，我们为什么不选择自己给自己洗脑呢？我想到了李笑来也提倡洗脑，给自己洗脑，洗洗更健康。所以我很佩服与神对话的勇气，很多书都是剖析一大堆，给的解决方法却很潦草，但此书给的解决方法非常具有可操作性，也绝不是泛泛而谈敷衍了事，我不知道那些觉得与神对话是扯淡的人，是否在读书的时候真的动过脑子。
* 是真的。我是71年出生，再过几个月就过50岁生日了。
我想绝大多数人看我写的这个都会有难以置信的感觉。我的人生经历确实有些复杂多变。一个人活着，在精神世界里所能失去的东西，我都曾舍弃殆尽。其实我在物质上并未吃过太大的苦，但是内心曾被折断千回，这是实实在在的。这些人生客观变化导致的内心遭遇，把我锤炼的已经很难有什么事能让我内心起波澜了。相比之下，痛苦和死亡对我来说根本不算多大个事儿。
我属于比较少见的那种人，能够按照年少时候的初心一直走下来。有点像电视剧，但这种事的确存在。包括我的哥哥们，亲人，朋友，同事，所有接触过我的人，都觉得我是个特殊的存在，无一例外。
我一直一个人生活。说是50岁，其实内心里和30岁的人差不多，而且很多小时候幼稚单纯的特质被我一直保留到现在。我的成熟和正常成年人定义的成熟完全不一样，我和同龄人可以说有巨大代沟。
背后的奥妙在哪呢？就是实践。书本上理论上人们夸夸其谈的人生哲理太多了，都有道理，但是真正敢于自己这么做的人很少，因为大家害怕代价巨大，恐惧。我只是真的去做了，并且一直走到底。当我能做到的时候，事情就很简单，非常接地气，不再是理论上的虚幻。当做到的越来越多，逐渐的就把虚幻的说法变成现实。同时这样的过程会让我非常清楚自己内心的真相是什么，到底要什么，所以舍弃不需要的东西就非常容易。而这在没有进行过这种人生活法实践的人，就觉得这比较扯或者匪夷所思。这就和人们不同圈子，不同贫富，不同世界的人很难理解彼此一样。没亲身实践过，就觉得难以理解。事实上只要做到就很简单。不做就觉得遥远。
* 1、扪心自问—找差异化：我和别人有什么不同，做这件事怎样才能和别人不一样，怎样才能比别人做的好？
2、换位思考—研究别人的心理：我这样做别人会怎么想？如果我是**，我会怎么去想？
3、决策树—逐层分解：做/想任何事情，剥茧抽丝，分解，分解，再分解，各个击破
4、天下没有搞不定的事情：每次遇到难以解决的问题，我会告诉自己，没有什么搞不定的，给我登月的资源我就能做到登月的事；最底线，熬过了时间就是胜利。

* 1. 学标杆—— 麦肯锡
2. 迅速将市场机会转化为商业模式——产品线、业务包
3. 做长跑的准备——专业知识管理、平台建设
4. 建设平台——案例、数据、模型、专家、平台
5. 比较优势——核心竞争力
6. 统一价值观——客户导向
* 推荐两本书 The Power of Less 和 Focus， 作者是http://zenhabits.net的博主，如果能严格按照书中推荐的尽可能做最少的事并且专注，必能高效的解决问题并取得意想不到的收获。
* 1、自我服务偏见：相信自己比别人拥有更多的天赋和积极的品质能使我们对自己保持良好的感觉，而且这种感觉能帮助我们应付日常生活中的压力；
2、态度决定行为，行为也会更加坚定你的态度，所以知行合一很重要；
3、少关注自我形象，你被关注的几率没有你想象的那么高，多关注自己的才能和人际关系，才会带来更多的幸福感；
4、适应性偏见：许多重大的消极的事件带给你的痛苦，没有你想象的那么严重。同样，兴奋的事情也不会给你带来更多更持久的快乐感；
5、群体的力量会更容易引发犯罪及不道德的事情，因为进入群体的人，在群体的压力和集体潜意识机制的作用下，会丧失理性，没有推理能力，思想情感易受旁人的暗示及传染，变得极端、狂热，不能容忍对立意见，因人多势众产生的力量感会让他失去自控；
6、群体会减弱其中的个体对事件的关注程度，他们都认为别人会有所反映，比如“见死不救”；
7、乐观的心态和人的寿命是正相关的，所以大家要天天快乐~

1、对客观行为的归因（协变理论）：一个行为随着某个因素的出现而出现，随着这个因素的不出现而不出现，人们就会把该因素归为该行为的原因。
2、对他人行为的归因（基本归因错误）：对他们的行为倾向于责怪人而不是责怪环境，即考察某些行为的原因时会高估人的主观原因，低估情境性因素。
3、对自己行为的归因（自利性偏差）：对于成功倾向归因于自己，而对失败则偏向归因于环境。 

再谈谈比较冷门的谈判学，虽然比较冷，但是非常实用：
1、当你出价时，开价要高，要高出对方的心理预期；最好是先让对方报价后再猛压价，同时永远不要接受第一次报价 ；
2、心中一定要事先想好一个最低价；
3、 时间压力：谈判中，双方所作出的80%的让步都是在最后20%的谈判时间当中完成的，应该在谈判刚开始时就把所有的细节问题都提出来；
4、如果对方给与时间压力，可以斥诸更高权威来为自己赢得时间（比如需要上级部门审核等等）；
6、一定要把精力集中到具体的金额上，千万不要理会交易总额，也不要用百分比的思维进行思考；
7、最好能有一个黑脸和白脸，二者配合唱双簧的效果还是很好的；
8、避免指出对方错误（以及一切可能产生僵局的可能），先承认对方讲得有道理，然后再讲自己的理由与优势，谈判很忌讳伤对方的自尊；
9、如果已经产生了僵局，将分歧放到一边，讨论其他问题，但不要把焦点集中到一个问题上；或者调整谈判小组成员，调整谈判气氛（比如休息、午餐或谈论八卦），调整谈判态度；
10、逐步减少让步的幅度，不要在谈判一开始就作出让步，更不要报出所谓的“一口价”；
11、千万不可过于贪婪 ，永远不要贪小便宜，绝大多数都是陷阱~
* 老师曾经在作文课上说过：看到题目的第一眼想到的写作方向一定要扔掉，重新想。这是因为你第一个想到的是很多人也都会想到的，写起来固然容易，但是却千篇一律，难有深度。不论是命题作文，还是对生活的感悟小随笔，我都尽量使得自己能从全新的角度去看，去想。
在进行漫画创作的过程中，我也依然践行这一准则。思维这就像发散的树枝，不停寻找，不停的深入，总有一个枝桠，站在上面你能看到最不同的风景。

* 从数学比较理性的角度，我们深知做出一个足够科学合理的决策或选择是需要成本和代价的；
同时，因为对心理学社会学及其他知识的粗浅了解，我很认同“环境以及主观因素对人的影响极其大”这种观点。也就是说，在大多数时候我们都带着强烈的感情色彩和主观偏好性以
及个体价值倾向来做决策和选择 - 这也符合人们在社会中的诉求，但矛盾的是人们同时希望自己的决策和选择是尽可能接近绝对合理和科学的 。 所以，我个人在实践中，一般是将
面对的问题简单化，然后识别出主次要部分，然后量化地去权衡
# 比如：人们在沟通中经常把充分条件或必要条件等同于充要条件，从而引发各种误会甚至争论吵架。
# 又比如，人们在多目标决策中，经常会忽略一致性检验，具体：当你关注的目标超过7个时，人们可能会给出与自己前述答案完全相反的结论，也就是自我矛盾，但这时人们并不自知。 
# 再比如人们对数论相关的各种争论和误会：一般人不太清楚可数和不可数的概念区别，所以如果你问他：是0-1之间的数多呢，还是1-无穷大 之间的数多？ 很多人都会迷茫，比如0-1之间的每一个数的倒数都可以映射到1-无穷大啊，是不是一样多啊。 那你又问他：0-1时间的数多呢，还是1-2之间的数多呢？ 他又迷茫，刚才好像答错了。。。最后他自己也搞不清楚了 。[有朋友对这个比较有兴趣，建议阅读“连续统的不可数性”]
再补充一个问题：关于三大论的，系统论，控制论，信息论。 
# 不是所有理工科的人都知道三大论，知道也不一定学习，学习也不一定深究。不过在我看来，理工科的人都应该去了解一下；这些理论知识非常有助于你的思维方式，让你尽可能考虑科学的方法方式，而不是凭感觉拍脑袋等。 
# 钱学森，大多人可能知道他的一些牛X贡献，部分人可能还知道除了火箭他还研究经济学等，看似不搭嘎，实则大道至简：他真正牛X的就是在系统工程方面的研究和贡献，极大地推动了国内在系统科学方面的发展。 
# 信息论，大多数人都知道Shannon，实际上信息论是非常重要的基础理论， 尤其在信息时代 ；做统计和数据分析的，大多会知道信息熵，这些相关的内容和方法都来自信息论！ 信息熵可以简单粗暴地认为就是一个对信息的度量单位和工具！ ... 打住吧，说起来没完了，犹如吹牛般...
又补充一个：条理性 
# 至少对于大多数人在学习和生活中，条理性可以极大地提高效率； 
# 条理性让你在学生时代会脱颖而出：小学和中学阶段的大部分知识，条理性极强，甚至对于零散的知识只要善于总结也可以条理化； 这就是我在某些阶段学习成绩还不差的唯一法宝，尽管别人看来我不是个好学和勤奋的人，但成绩不差(有事没事还来个名列前茅)； 
# 条理性让你会主动去了解和学习 GTD 之类的相关内容，让你关注效率等，对生活和工作都很有益。 
# 条理性也有弊端：比如一些人因此会变得不擅长写文章不擅长比较文学和文艺方面的事情(只是一些人，不是所有)。 他们就算写文章，也是1,2,3，A,B,C这样罗列，层次分明，无法接受一锅煮；这个类型的LEADER也无法接受下属提交的密密麻麻一堆文字的文案或报告...

* 我来补充一个修行方面的答案。
人在社会中沉浮，很容易就意识到生命的奇妙，便展开探索之心；或是意识到人生苦痛无常，于是生出出离心。这两种心是修行的基础。但这只是迈出了第一步，等在后面的是一长串的陷阱（就像红尘中的事物一样，哪一样又不是误区重重呢？）大多数人在不同的阶段都投靠了易经、老庄思想、养生、大乘佛教或各式各样的玄学和宗教，其实都是贪心的产物，没有完全解决人性的弱点，又如何修出凡尘呢？以上所列的各式“出路”，都是博大精深，足以把一个人绕在里面很多年。
所以这里我想揭示的一个规律是：我们可以借由那些玄之又玄的理论去探索更大的人生，但是永远要保持严谨的逻辑，和独立的思考。目前受过训练的、能解决社会中纷繁事情的大脑反而更有力量去探索形而上的理论。严密的逻辑对于超世的追求不是矛盾，而是它的基础。

* 1，能够把简单的事情想复杂。使你具备执行力。
2，能够把复杂的事情想简单。使你具备操控局面的能力。

把简单的事情想复杂。比如，你和老板约定，明天早上9点见面，老板还没有告诉你谈话内容。这件事看来很简单，无非是明天早上见面听老板说话，根据情况应对就好了。但是，要怎么把它想复杂呢？ 
1，为了保证见面准时，你要记得上闹钟。一般你在闹一遍时可以醒来吗？如果需要两个闹钟，也请准备好。如果没有两个闹钟，可以用手机闹。 
2，为了确定准确的闹钟时间，你要考虑，一般你是几点必须出发才能不迟到？你的洗漱时间多久？你会因为上厕所而耽误时间吗？
3，你准备好明天早上的服装了吗？着装符合公司规定吗？背什么包？
4，你预计老板要和你谈什么了吗？你要猜一遍，并有所准备。年关将至，公司准备提拔你？准备炒你？总结2011年的工作？向你了解部门状况？调换工作？老板有私事请你帮忙？有新的工作任务要你介入？要关心你的私人生活？各种吧，要猜一遍并有应对的准备。 
5，这个见面谈话的机会，你有事要向老板汇报吗？这是个好机会，请你善用。 
以上是把事情想复杂的过程。如果你按照这个复杂的状况做了准备，你会有比较好的谈话结果。这个过程本身就体现了你的执行力——能够把这一次和老板的谈话做好。 
有了这种思维能力之后，还会面临怎么把这种能力运用好的问题。
* 第一，拒绝特例。中国有一堆千奇百怪的经济问题，许多问题在别的国家根本见不到，但这并不说明中国人和世界人民有什么不一样的地方，所以别总把想不通的问题往特例的圈里套。这么做很轻松，但是对逼近事实毫无益处，反而可能让你找到的解决方案南辕北辙。两个最近的例子，中国生育率高——因为中国人的传统就是养儿防老；中国储蓄率高——因为中国人不喜欢借钱，而且喜欢省钱存下来。现在看看，中国的生育率还高吗？家庭部门的储蓄率还高吗？尽管如此，特例说仍然很有市场，最近的一个例子是，为什么房价高？——因为中国人对房子是刚需。拒绝特例，类似的还有拒绝阴谋论，可能会增加你思考的强度，但更会增加你接近事实的概率。
第二，慎言因果。伪回归，内生性……在你使用数据得出因果结论时，一个个陷阱正等着你。回答几个直白的问题，1）缩小班级规模有利于提高教育质量吗？从数据看来，即使师资相同，小班的表现也更好，答案似乎很明显，但如果你回答“是"，那就犯了伪回归的错误。经济学家发现，所谓小班带来教育质量提高，仅仅在那些大多数保持大班，只试验了几个小班的学校存在，小班试验的份额越大，教育质量提高越不显著，甚至会相反。原来，那些被编入小班的同学都觉得“原来自己是被选中的”，所以学习更努力，”被选中“的人越多，这种效应越小。当全校都是小班时，这种自我期望的提高就消失。只可惜当经济学家发现这个问题时，美国早已经推行小班十几年了。2）技能培训能提高工人工资吗？你拿出两组工人，一组参加了技能培训一组没有，必然参加技能培训的人工资更高。但是，这些工资的提高往往是因为更努力，更上进这些个人特征而更倾向于参加技能培训，即使没有培训，他们的工资也会因为他们的个人特征而提高，这就是内生性的问题，他会在一定程度上削弱你想证明的因果关系。所以，下一次在你的ppt中信心满满地放上相关性极高的散点图或折线图想要证明一个因果问题时，记得把整个逻辑都理顺，多问自己，有没有伪回归？有没有内生性？
* “当事实对你有利时，多强调事实；当法律对你有利时，多强调法律；当事实和法律都对你不利时，敲桌子把事情搅浑”（When you have the facts on your side, pound on the facts. When the law is on your side, pound on the law. When neither the law nor the facts are on your side, pound on the table.）。 

这句格言不仅在诉讼或谈判中有用，在旁观各种复杂的纷争时，我也总是尽力在分辨，谁在讲事实，谁在讲道理，谁只是把桌子拍得震天响

* 工程师：
1。简洁是天才的姐妹(Keep It Simple Stupid)：每个人可能学过的东西很多，但要时刻记得用最简单的方法：最简单的方法实现，最简单的方法解释，最简单的方法演示，最简单的方法维护。在工作中多次见到设计者为了展示自己的知识丰富、技术高超，用复杂的技术来解决简单的问题，结果给前期的审批，中期施工，后期的维护都带来巨大的问题。
2。不怕有问题，就怕没问题：工程师在设计施工时，不怕发现问题，就怕发现不了问题。发现了问题就知道怎么解决，如果没发现问题，那就一定会出问题的（墨菲定律），出问题的时候你就抓瞎了。
3。我们不是研究问题的，是解决问题的：上学的时候，大家都学过各种模型、假说等等。那都是抽象的，和实际对不上，实际问题和模型假说等有出入，工程师就是解决这些出入的。任何你所知道的东西都是你的工具，但你没有任何借口——包括“没有办法”也不是你的借口，你必须要解决问题。比如高次方程没有解析解，工程师忘掉定性分析的问题，用数值方法来搞定；阶跃函数无法求导，工程师不管函数的严格定义，直接用德尔塔函数来帮忙；非线性的问题缺乏数学工具，就在某一点附近取线性近似……总之能解决问题为准。
4。实践是检验真理的唯一标准：你的设计采用了最先进的技术？经过了反复理论论证？多位专家持肯定态度？业界已经普遍采用？你上一家公司也是这么设计的？对不起，没有用，做出来为准。再好的设计在施工验收完成之前都是纸上谈兵，用过再多次的设计在施工时一定会出现新的问题。设计完了只是开端，施工验收完毕，稳定运行一段时间才算真的设计成功。

IT行业：
1。变化是唯一不变的东西：什么都在变，三五年就出现一茬新技术，跟着技术的发展客户的要求也变了，供货商的政策也变了，连公司内部的人事结构……这些事情在大型的IT项目里是家常便饭。所以在项目开始之前就要做好事情发生改变的准备，尤其是主要的技术趋势转变，自己公司、供货商以及客户公司内部的变化等等，后面这些功夫都在工作能力之外，人脉变得尤其重要。
2。拖也是一种工作方法：这一点应该任何行业都适用的，不过在IT行业由于变化显得尤其重要，比如你知道事情一定会发生重大变化，但是变化是什么还不清楚的时候；或者你明知道客户的要求是无法企及或是有严重问题，而你公司一方又要求你满足客户要求的时候，最好的办法就是拖。
3。越简单的东西越难通过。IT人往往对非常简单的项目不重视，PPT，文档，乃至邮件都草草了事。结果往往是通不过。（我同事曾经做过一个把百兆以太网升级成千兆的项目，去了七次技术讨论会方案还没有得到通过。）要知道最后拍板的人大都是对技术不熟的人，他们根本无法判断一个项目简单还是复杂，如果你给的材料不足，他们就会认为你没做好准备，不会给你通过。

* 机械工程：所有科学理性的思考计算得出的工程结论，都要加上极大的裕度，才能投入生产使用 ---- 知识越多，对自然的敬畏之心越大。

* 1、写论文的时候： 
论点创新和论据创新哪个更重要？大多数时候，我们会尝试论点创新，但事实上论点创新是非常难的，也很少见，因此实际操作的时候，论据创新更加重要，也就是你用来论证观点的材料挖掘。 

2、学习： 
一、任何事物的学习总是循序渐进和反复的阶段性过程，；一段时间你感觉突破了，非常顺利，前面的视域很开阔，但是不要着急，一段时间后，你就会发现，原来山外有山，而你怎么都迈不过去那个阶段，这个时候就继续苦读和练习，不管是绘画也好，设计也好，理论也好，都是一样的。 
二、还有学习的方法和习惯比学习知识更重要，因为学习是终身的，当你离开学校，你要自己学会学习，这需要良好的学习习惯，和学习方法。 
三、成绩不重要 

3、美是需要教育的 
美，或者说审美，是需要教育的，陈丹青说过，美术馆里面最美的那幅画会抢人的视线。但是，如果你没有经历过美德教育过程（可以是被教育，也可以是自我教育），你是很难看出来那幅图最美和为什么最美的。好比毕加索的画，儿童也可以画出相似的线条，但是那不是艺术品，因为艺术需要系统的读解和创新。 

4、具体的设计方法 
一、注意网格对齐和空间留白 
二、注意设计说明 
三、比较比较再比较 

5、儿童时期 
儿童时期是我一生中最重要的时期，在这个时期，习惯，性格，气质，爱好逐渐成形，等长大之后就不会再有很大的变化了。 
我小的时候，觉得怎么书上说的和我想的差不多呢，那为什么我要读书，后来才明白，一件事情你直觉的明白和系统的明白并能阐述出来是不一样的。往往要花大时间在论证的过程上，要说清楚一个大家早已知道的道理就和论证1+1=2一样困难。 

6、新闻传播专业 
1、新闻专业在理论上是学不到什么东西的，有一些经验层次的东西，重点还是在实践。 
2、传播专业的理论在学习的时候觉得没用，但是在后期终身受用。 
3、编辑，什么样的编辑都有，但是大多说不清编辑是干啥的。 

7、记忆 
记忆是会骗人的。它会悄悄吃掉你不注意的部分。 

8、程序员 
程序员的能力是不一样的，同一件事情，实现的质量完全不一样。

* 1. 分解（分层、分模块） 
“把大象装进冰箱需要三个步骤”的笑话大家都知道。 
这并不只是笑话，这是很地道的分解问题的思维。 
在充斥着巨量细节的状态下，唯一靠谱的方式是通过分解问题来理顺思路、逐一解决。 

比如，就说让电脑上网看网页这事，其中就有多个层次的问题： 
首先，浏览器需要知道网页是什么、怎么用的，比如颜色、链接、网页布局、网页上的动态效果这些东西都是怎么表示的；然后，我们得确保网页是能获取到的，这就涉及到我们怎么通过域名找到服务器，跟服务器怎么“说”表示我们只是想看某个页面而不是想发QQ消息；但这些的前提是我们的机器能跟网站的机器“好好沟通”，听说过“网关”/“路由”这些概念的人都知道，机器间的交流都是通过中间的机器一次一次的转发做到的，那么应该怎么保证消息在机器间传递，最终会传到；再往下想，我们成功地设计出了一种消息格式，但实际上需要通过网线上的电信号表达出来，那么应该用什么样的信号在什么样的网线上传输，可以做到节省材料、减少干扰、稍微长点的距离也能用。在其中的每个层次，都有很多细节，但分清了层次，层外就可以忽略这些细节。 

这种思路的本质是：通过合并减少问题数量，通过拆分减少问题间的联系，从而能做到“批量”、“宏观”地解决问题。 
分解成功的标准是高内聚、低耦合：说白了就是，分在一起的确实有很强的内在联系，而被分开的联系都很弱（专业术语叫高内聚、低耦合） 
危险是，有时候底层细节并不能简单地忽略，但分层会造成一种“可以忽略底层”的假象。比如网络中每层都可能存在安全问题，并不容易“封”住不暴露给上层。 

2. 缓存（cache/buffer） 
据说有些宅会一星期大采购一次，然后一星期不用出门；或者有些人很喜欢做读书笔记。 
这都可以看成是一种缓存。 

计算机里，由于各种设备速度差别很大，缓存无处不在。 
比如，如果你能分清“内存”和“硬盘”、知道硬盘速度比内存慢很多，就比较好理解：装软件都是装在硬盘中的，但运行程序却是要先加载到内存中再使用，修改word文件时也是在内存中修改，自动或手动地写回硬盘 
再比如，网络的速度比硬盘慢很多，所以浏览器都会把网页缓存在硬盘上，所以会有我们能看到的“清缓存”操作 
再比如，google其实是一个互联网的“大缓存” 

缓存的本质是：在能够预测未来使用的前提下，预先存储一些处理结果提供快速访问，从而做到用空间换时间或缓解瓶颈。 
而缓存从逻辑上就会存在数据陈旧的问题，比如电话本里的号码可能已经停机了。 
而从逻辑上有两种解决方式：一种是当数据有修改时锁定记录并做到同步更新（要求别人换号时必须立即通知你）；另一种是设置过期策略，保证不会过期太久（每次过年打一遍电话check）
* MECE (Mutually Exclusive and Collectively Exhaustive)
这是一种在分析问题的所有方面，或者穷举所有实例时，做到不重复且不遗漏的方法。来自麦肯锡咨询的知识积累。具体做法是把问题逐级分类，每步都尽量考虑到所有方面，最终形成一个树形图，把问题的表象分为细致层面的每个小问题。 
举个例子。 
例如我们在分析“环保局为什么不公布PM2.5数据”时，用MECE的方法分层： 
1. 主观不愿意 和 客观不能够 
2. 主观：内部主观原因 和 外部主观原因 
客观：监测硬件原因 和 监测软件原因 
3. 内部主观原因：对环保局内部无大利益 和 对环保局内部有损害 
外部主观原因：上层单位命令 和 下层单位需要 
硬件原因：没有监测设备 和 设备无法使用 
软件原因：没有收集能力 和 没有分析能力 
4. ...... 
这个过程每个人在做时都会有一定区别，但至少能够保证分析过程中对问题的方方面面无一遗漏。这对于解决复杂问题和现象是必不可少的。 

2.如何提问题、分析问题、解决问题。 
这个...说起来也是很有技巧的。 
能问出好问题的人才算是好学生，这句话非常多人都在说，尤其是在国外。但很可惜地，有我国特色的教育制度决定了，问“怪问题”的同学应该楼道罚站并请家长。所以大多数情况下，我们看到没大脑的记者们在地震灾区追着灾民问“生活有没有困难”，在媒体发布会上娱记被姜大爷冯大爷几次欲饱以老拳。当然，也许挨揍也是某些娱记的工作之一。 

我们这里不说广义的“问题”，单单说严肃的、认真的“问题”。 
问题的提出首先要明确：问题的提出是要找出目前困境的解决方法，通过逻辑推理来挖掘困境的本质。而如何定义问题，就是开始解决问题的第一步。 
而在咨询行业里，会用一种金字塔结构去定义问题，其中仍然会用到MECE方法。而区别在于，要把每个方面都转化成一个“合理的质疑”Reasonable question。并通过建立这些质疑的清单，来逐条理清目前的状况，最终留下一个包含了 清晰的问题清单 以及 问题之间的逻辑脉络 的图表。 
有了问题，下一步就应该是如何解决问题。这里我建议参考另外一个问题： 
* 科学和工程计算领域：化简和近似。 

尽管在实践中使用的科学和工程公式，几乎都已经不是完全精确的描述了，但把这些公式直接而不加处理地运用到复杂的现实问题中时还是经常会出现一些复杂到爆，完全无法接受的结果。 
公式往往是在一种简单的情景下推导出的纯粹的形式，一旦加上边界条件、初始参数、各种修正、以及方程组的联立之后就完全不一样了。举个例子，曾经在某次数模竞赛中用几个简单的函数建了模，最后联立求最优解，试了一下用Mathematica直接解出精确的解析解，结果有上万项（UPDATE：重新调出了当时的数据看了一下，总共14376项，输出共2000多行，也就是打一个式子就有几十页），完全没法用。 

这种情况下就要求科研工作者必须掌握合理的化简和近似技巧，找出变量间的暗含关系，忽略次要的变量而保留主要因素。这一方面是有规可循的，另一方面也常常表现为经验的作用，需要一点积累得来的感觉。工程方面，了解得比较多的就是模拟电路方面，有经验的人一眼或者简单计算一下就能找出问题，而这些问题用纯计算的方法是很难快速解决的。 

俄罗斯人在科研上貌似比较擅长这一点。我一门课的老师跟我聊过，他们做科研时和俄罗斯人合作过几次，因为俄罗斯人擅长解方程（主要的功力就在近似上，近似之后方程才是可计算的，否则没法用），而中国人相对比较弱，搞不定数学，就负责做实验了。（他们是做光纤波导的，不是理论物理，解方程是为了预先选取实验参数。） 

当然算法和计算能力的进步肯定对解的精确性有帮助，但现实问题的复杂性也是在不断上升的，恐怕一段时间内近似还将是一种重要的思维方式。而且，通过近似化简得出的方程往往更加简明，物理图像更鲜明。
* 在日常维修时，常会遇到生锈的螺丝，以至于连螺栓松动剂也 无可耐何。
这时老师傅就会拿榔头对螺丝敲两下，再用扳手往里紧半圈再松开，于是螺丝就这样松动了。
问老师傅为何这样做，老师傅便说： 我师傅就这样教的。
从这个事情上来看，事不大，但却有大学问。

1 逆向思维 很多人遇到螺丝锈死，第一反应是用扳手往松拧，拧不动，就会觉得自己没有使出足够的力气，于是就一味的加大力气往松开的方向上拧，以至于把螺母或螺栓头拧圆了也未能拧开。这样的情况是因为陷入一个误区，认为锈死的螺栓只能往松开拧。其实，由于设计原因，螺丝扣的三角形截面形状所限制，只能有一面是紧贴着的，三角形截面的另一边会有间隙，这个重要的情况往往被人忽视，包括搞机械加工和维修的人员。老师傅的敲击并紧固半圈的方式，正是利用了这个误区。
逆向思维理论很多人都知道也都学过，但有很多人在实践中，往往被固有的惯性思维方式所禁锢，看不到面临问题中误区。这种方法，我用的比较多。（另我幼稚的是：我由于使用成为习惯，导致我看问题时往牛角里钻，让我看问题不够全面，言论显得极为偏激和幼稚，我在慢慢改正）
2 缺乏分析 用螺丝紧固的物品大都是金属和木质等的固体，在长期的使用过程中，被氧化而生锈，但，对于金属固件，还有一个问题，那就是热胀冷缩所带来的微量应力变形。老师傅的敲击，消除了这种应力变形，对于松开螺丝有很大的帮助。在做回头分析时，方恍然大悟。
缺乏细致的分析和判断，导致耗费了大量的时间和人力物力，却没有得到好的效果和回报。这在日常工作时候，经常能看到。

面对问题，正确的解决之道是一个大家都渴望得到的能力。但在成长过程中，我学习到了很多知识，但却渐渐失去了仔细观察和认真思考，太浮躁太浮躁了。
每当我遇到困难时，我总会想起这个螺丝生锈的事情
* <从量化投资研究得到的心得> 很多事情的结果 r 是由成千上万个因素 X1，X2，... X10000，... 共同决定的：
r = f(X1,X2,X3,...,X10000,...) 我们每个人都能观察到或控制住其中少数几个决定变量。
对所有人都关心的事情，例如投资，所有人都在最大程度地根据自己能掌控的那几个变量来
和其它人竞争，在这种充分竞争下，没有人有绝对优势。一个经验原则是：投资结果是由5%
的技术和95%的运气共同决定的，也就是说，即使你有绝对技术优势，并充分努力，你也之
比别人的胜率高一点点。

这条心得帮助我：在获得成绩时，让自己冷静，因为有95%是评运气，只有5%是技术真的比别人好；在失败时，让自己振作，因为一次失败不说明自己比别人差。

* 处理客户投诉的基本方法
①聆听：了解客户需求，得处理投诉的重要信息。
②尊重：给足顾客面子，平息顾客负面情绪。
③询问：找出问题所在，为提供解决方案收集信息。
④解释：澄清事实，提供解决方案。
⑤解决：满足顾客需求。
⑥增值：解决方案﹥顾客的期望值。
⑦记录：汇总信息、总结经验。 
* 心理咨询师，简单说说。
（1）人生无常，各种痛苦体验就是人生的一部分。逃避会让痛苦体验加倍，而接受会让痛苦有一种庄重尊严感。坦然面对痛苦是摆脱折磨的必经之路。从决定接受痛苦开始，你步入修行。
（2）人生总有缺憾，成熟就是接受自己的缺憾和有限性。你越是在意缺憾，它限制你就越多。只有接受，才有放下和超越。
（3）心理咨询师能做的，不是让你摆脱痛苦，而是让你摆脱自我折磨。
（4）越是能解释一切的心理学理论，其科学性就越可疑。越是包治百病的治疗技术，其疗效就越可疑。越是什么都懂得人，其结论就越可疑。
（5）心理咨询中起作用的很大一部分是咨询师和你的关系。如果你觉得咨询师和你不搭，咨询一定不会有效。
（6） 春天的花，秋天的月，美好的爱情，广阔的世界，这些都不需要你先把心理问题解决好了才能去追求和得到。相反，它们本身就是心理问题的解决之道。
（7） 一个好朋友常常比心理咨询师对你的帮助更大。

临床心理学诊疗时有一个基本原则，对于抑郁或者焦虑症患者来说是盲点——你要接受这些负面情绪，而不要企图将其完全消除。负面情绪之所以庞大或者强烈到让人无法忍受，是因为我们太在意它，或者觉得它太过强烈。ACT疗法的第一个词acceptance就是训练患者接受这些你无法控制的东西。

* 关于投诉、信访、报案、打官司等纠纷解决
“xxx部门不作为啊，太黑暗啊” “这个问题我投诉了好多年都没有解决啊，不公道”。工作中接触到大量案例，有些人“维权”多年，一直在投诉举报对手和相关部门，但事情却没有实质性进展，自己变成怨男怨女，空抱怨。
1. 有关部门“应该”处理你的问题，但永远不要假设他们会自发地做，他们一切动力来自上级，包括考核、任务、维稳、法律等压力。为什么报警要打110，不要直接打派出所电话，因为市局规定110分配下来的事情一定要出警，出警后要给当事人回执，且110会记下报警时间和出警时间。而派出所接电话的人可以懒得理你。
2.任何解决问题的许诺，若不给你部门落款盖章的书面答复、协议、文件，基本不算数。不要想着“那个局长、主任亲口说的，我有录音”，这都是拿不上台面的无效证据。
3.世界上没有谁天然会替你主持公道，把这个希望寄托给天朝更是徒劳。一切纠纷解决的实质在于谈判，你得知道自己手上的关键筹码、对方的弱点，以及你要求助对象的弱点和利益所在。比如拆迁，必须守住你的房子不被拆，你能要到的最高价是在房子被拆、临近最后期限前。如果没守住，你的筹码是大城市上访或媒体，不是让你真的去上访，但你要知道当地administrator怕的是什么，你才能要到更高的价格。
4.法院判赔偿数额，只看两样东西：法律明确规定赔偿标准，以及已经给你造成的有发票、票据等有依据的损失。换言之，机会损失是不算。所以不管你是千万巨富还是流浪儿，你被冤枉羁押，国家赔偿的标准都是坑爹的每天多少钱。你说“如果我不被羁押，在外面一天能赚多少钱”，这个损失没人管你。同样，你的房子被强拆，补偿拖了几年没解决。这期间开发商在你家原址建起房子出租，你想要那租金吗，没门。如果你丧失了主要筹码，拖的时间越长对你越不利。
5.只要有善意第三人，你被侵占的东西基本不可能要回来。若开发商强拆你的房子再转租、转卖给他人，你已经失去谈判大部分筹码。
6.任何涉及重大利益、有可能出现纠纷的事情上，从一开始就收集书面证据，咨询律师，法院是最后可以解决问题的地方，也是最漫长、成本最大的地方。靠谱的律师会告诉你可操作的办法，怎么能办成事。打官司不一定能赢，但会是把事情公开，坐下来谈判的合适平台。要是能立案的话，法院一般会尽力调解，协助双方达成协议。一来法院有结案率和审理期限的要求，二来法院不愿意把别人的事情变成了自己的维稳问题。
7.法院判案除了参照你能公开见到的民法刑法诉讼法等，更多的是参照“最高院内部会议纪要”“关于某某问题的审判指导意见””，一般人根本不知道这些“内部法”才是效力最大的判案依据，这些文件甚至直接确定哪一类的案件法院不能立案。好的律师会知道这些文件，并且找到这些文件中对你有利的条文。
8.判决是一回事，执行是另外一回事。没谁能给你保证执行结果。赢了白赢的情况比比皆是。
9.如果你已经失去能威胁到对方的筹码，官司输了，媒体找了，都不行，你只剩下“天理”“公道”在手，还是接受对方的报价，赶紧恢复自己的生活吧
* 设计/用户体验类：
为容易误操作的事情增加难度。 比如删除文件时弹出的是否删除对话框、 残疾人学校的门锁在门的最上面等等。
不要把不同功能的按钮设计得一样，摆得太近。按钮排列要分组。除了利用颜色来区分，还可以加入大小、形状、触感、反馈等区分元素。例子：司机开车时要看前面，如果操作按钮摸起来一样或靠得太近，他就要低头或容易误操作。
符合用户的心智模型。如果是竞争品，不要妄想扭转用户的使用习惯；如果是新品，不要跟用户的思维作对。
古腾堡图表——用户浏览网页的视线轨迹是从左上到右下的对角线，左下和右上是用户的视线盲点，不要放置重要的信息或功能。 图：http://www.douban.com/note/82808447/
用户会被文案和色彩影响行为。例子：一网站把“立即注册”改为“免费注册”，注册量增加了二十多个（大约）百分点；把按钮色彩从蓝色改为红色，会刺激人点击。
标准应尽早订，但也应尽量晚订。标准是在大家都没有一个更好的设计方案时，制定出来强制人们遵守的规条。当有很多竞品时，你做你的我做我的，各自一套思路，谁也说服不了谁，自由意志得到体现这很好，但是用户会感到很混乱、不方便。这时，在没有一个更好的让每一个人都满意的设计方案出现前，行业内订约，设定标准，遏止混乱。但是标准太早设定，不利于设计的进化和革新。
一切错都是设计者的错。用户不必感到自己很蠢，责怪自己。（唐纳德《设计心理学》整本就是讲这一个内容。）
产品的迭代过程总是从简单到复杂，再回归简单。早期技术还不成熟，大家忙着开发完善技术，不停地添加功能，人要适应机器；后期，技术渐趋成熟，可以不为功能牺牲人的感受了。
感觉不到有设计过的设计才是好的设计。
听用户的反馈，但别听信他们的反馈。当用户抱怨，那一定是有问题，但问题不一定出在他们说的地方，他们提出的建议也不一定就是真正的解决之道。
只要是参与设计的人，就不是用户。 “你不是用户”这句话本来很好，但被某些设计者拿来当挡箭牌反驳别人的建议。“我”不是用户是什么呢？我既然没有参与设计，我就是用户。
以B比A更差来反对改变A，是没有想象力的表现，这个世界上还有CDEF…

* 历史学的一种思维方式 解构和构建 

1，很多人认为历史学其实只要知道史实，然后把史实串联起来，再加以评论 
2，大部分初学历史的人则认为历史学是需要大量的史料，然后把史料组合起来，串联史实，再进行评论 
3，其实历史学是一种“分析问题”的学科，这个从程序上来说就是"提出问题，挖掘问题根源，解构概念，构建逻辑，解释问题。”，而最终想要达到的结果就是希望寻找“论证准确的反常识”。这里只涉及理论，不涉及史料学，史料学是一个技术活和体力活。 
================================================= 
1，提出问题和挖掘问题根源。 
提出问题不仅仅是说提出自己的疑问。首先，大部分疑问都是伪问题，只是建立在对问题所涉及概念不熟悉的基础上造成的误解。第二，另一部分疑问是无法解答，这些无法解答原因可能很多，比如这个问题史料严重不足，或者这个问题涉及面太广，明显超越了这个人现在的能力（这个其实很主观的，说白了就是只要问题准确，没有不能解决的问题，只是在精力上和效率上不值得） 
这两个判断问题是否成立的步骤就是挖掘问题根源 
2，解构概念。 
要弄清楚自己所提出的问题，首先必须对问题涉及的概念进行解构，这个解构一方面是逻辑上的解构，仔细重新思考这个概念是否是本元的概念，还是由别的概念构成的，或者衍生的概念，或者是被人灌输的概念，当然其实基本上没有什么本元的概念，所以这个步骤可以算是概念的溯源，这是重新定义概念内涵的过程。 
其次是对这个概念的适用范围进行解构，基本上没有什么概念是普世的，在不同的问题上同一个概念其内涵可能非常不同，所以在要重新审视在上一步中所重新定义了的概念其适用的范围有多大，是不是能够覆盖要解决问题的范围，不行的话就从上一步重新开始，这是重新划分概念外延的过程。 
3，全新的概念必然会带来全新的逻辑，这个是正常的逻辑推理过程，其方法很多，不外乎归纳与演绎。 
4，然后在全新的概念下和逻辑下重新解释问题。 
================================================== 

所以，其实对于历史学来说，最重要的其实是“重新构建概念”这个步骤，这是思考问题的基础。 

个人觉得这个方法对解决很多问题都很有帮助。

* 画素描和水粉的时候，从简到繁，先是景物的形，然后是层层丰富渲染，任何时候，画都有整体感和美感。先有整体再有局部，能够时时审视和修正，不容易偏离本来的方向。另外，从开始就构建了完整的形，任何时候看都是完整的，只是开始粗放，后来细致，这样做画很容易获得成就感。 
画国画考验基本功，平时在草纸上反复练习，做画时，先有腹稿，落到纸上从上到下，从左至右，一气呵成，所谓胸有成竹。画坏了只能重来，没有后悔的机会。机会只给有准备的人的，而人一生中也就只有几次重要的机会。 
烹饪时要做出健康美味，要熟悉食材的四性、五味和五色，主料辅以佐料，互补搭配，掌握火候，才能成一盘营养好菜。这和用人有异曲同工之妙。 
程序设计领域，UML的需求分析方法中，把系统当作一个黑盒来研究，先定义系统的边界，再寻找角色和用例，用例表达了这个系统对外部可见的行为。这种分析方法能够简化问题，理清纷乱的关系，容易找到问题的本质。 
项目管理的WBS任务分解，是根据项目目标把工作分解成许多层次分明的、可交付的工作任务。它是按层次分解的，先定义大阶段或大目标，然后逐层分解细化。随着分解层数的深入，定义的项目任务就越来越详细和具体。WBS使得我们能对每个工作包的资源分配、交付物、交付期都心中有数。这种工作方法适合做估算。

* 知識之禍：一旦你學會了某種知識，就無法永遠無法體會不瞭解該知識時是什麼樣的情形。失去了初心。
換位思考的誤區：當涉及到人之常情的常識性問題時，換位思考會顯得更有同理心；但當涉及到人之間不同的觀念時，容易變成以己度人，例如家長把自己的理想強加到孩子身上等。一個人的行為有太多的因素決定，大多數連本人都察覺不到的潛意識，連自己都不知道自己行為的真正原因，更不用說換位思考了。
查理芒格自稱掌握超過一百種思維模型，他推崇跨學科的多元思維，說過一旦你也掌握這麼多思維模型你一定能成為一名智者。列出一些例如：“工程学的亢余系统模型、物理学的断裂点/颠覆力矩模型、生物学的现代达尔文合论模型、心理学的认知误判模型”。
我覺得雖然這個非常好的問題中有非常多的好答案。但許多人看過雖然感觸頗深但並不會產生真正的價值。思考的價值在於“你必须把经验悬挂在头脑中的一个由许多思维模型组成的框架上"

作者：马先

* 我是物理系专业的，来谈谈在《热力学与统计物理》中收获的东西吧。 
对于任何东西，作为一个人，一个非神的种类，进化的过程就是熵不断降低，有序度不断增加的过程。所以，会将对熵能够降低与有序度增加有无与比拟的追求。这可以看成对抗混乱与退化的一个手段。 
自然界，宇宙，乃至于人的世界，都是可以看成能量与物质的系统。对于一个系统，包括人，国家或者世界或者宇宙，都是一个开放性的系统，能量与物质既有输入也有输出，能量最低的状态往往是平衡状态，但往往也是高熵状态。有一种说法，在任何热力学过程乃至任何事件中，总的来说都是熵增的过程。整个宇宙最终会达到热寂的状态。但我觉得，我有这种信仰，说明宇宙的走向，包括宇宙中的万物（包括人），绝不是这样的。 
对于人来说，这里不说摄食与排泄的过程，只讲人的精神层面。人作为社会性动物，每天都在与人的沟通交流之中，输入新的观点，输出自己已有的观点，在今网络时代犹盛。对于人每个独立的个体来说，都该是处于一个好的平衡之中（这个好，是指人的精神状态，人的生存欲望，人的心理状况），必然是要有高的有序度与低的熵。人的世界，不同于我们惯常认知的客观世界，人内里的精神力量可以在好的平衡时不断地获取。作为一个想要保持在积极状态的人来说，必须要保持与人之间沟通渠道的顺畅，与自我沟通的顺畅，要保持外界信息的摄入，也要保持自我信息的了解与告知他人（其中运用的方式可以是语言，可以是文字，也可以不是即时传递）。在这样的过程中，在每天与外界的沟通交流过程中保持自己思想的不断更新，让自己保持在一个低熵且有序度高的平衡态。（心理学中也涉及到将熵应用到人的心理状态，如《少有人走的路》第一本。） 
待续。

* 一个人最核心的是思维，你可以读几本文学名著装点门面，但是思辨能力和对世界是什么，人是什么，我是谁这样的终极问题的追求是无法去装的。
爱英语专业的人会有这样的感觉：当你用一门语言打开另一个世界，你了解到的很多东西会颠覆以前的世界观，会发现以前被灌输的很多知识其实并不是那么正确的，在比较和思考的过程中，你会找到比别人更敏锐更深刻的视角来看待周围的世界，而当你将两种文化两个世界进行比较的时候，就已经开始独立思考了，这是英语专业很容易被人忽略的价值。

作者：酸菜鱼

* 笛卡尔的科学方法论，个人认为解决各种问题都会有相当帮助： 

绝不承认任何事物为真，对于我完全不怀疑的事物才视为真理；
必须将每个问题分成若干个简单的部分来处理；
思想必须从简单到复杂；
我们应该时常进行彻底的检查，确保没有遗漏任何东西。

* 通过背诵锻炼你的记忆力。
这是最早我在中学时学习外语时所采用的方法，彼时需要背诵大量英文课文，而且需要按照录音磁带的语音语调背诵，每年学校举办语音语调模仿比赛，就是背诵课文，比谁模仿得最像。看似枯燥，却为学习语言奠定了扎实的基础。
聪明人有很多，但聪明人的共同点之一是记忆力强。记忆力有天生的基础，但后天的锻炼却更为重要，甚至起到决定性的作用。背诵是锻炼记忆力的有效办法，虽然很辛苦。
有人会争辩我们的教育已经培养出一批死记硬背的人，还需要强调背诵么？其实灵活、创造性的运用知识和对知识的记忆本来就不是一个矛盾的话题，就像再有创造力的建筑也是从地基和一砖一瓦建起。创造力的开发是另外一个话题，但不能因此否定地基和砖瓦的重要性和基础性。

由此衍生出的一个常识就是：凡事要取得成就，总是需要大量基础性的工作，没有捷径。

很多人询问我如何学习好一门外语，我通常告诉他：找文章来背诵，背到滚瓜烂熟，这是起码的。如果连这点苦都不能吃，还是别学了。

正如有人询问我如何应对中国的考试，我的答案就是：疯狂做题。题海战术也许不是掌握知识的最佳途径，但确实是应试的必要路径。

作者：周自强

* 世界上相当多的人没有能力明确表达出自己的诉求。

* 【传媒行业/官方通讯社里你所不知道的】
总结成一句就是：同样是新闻，最可怕的在于你不知道这条新闻是来源于上面的红头文件，还是内部部署，还是来源于赞助，还是说只是记者的单纯发现。同样是一条新闻，如果最初的动机不同，背后则是天壤之别。
1.红头文件
这个通常是出于政治的褒贬考虑，不细说。
这个通常是来着于上面的意思，是出于某种导向原因来进行的，最典型的就是最近很火的某领导任人，在110年诞辰之际，突然涌现了很多很多的作品。从相关的文学作品到一套黄金时段的大型连续剧，各种大大对他高度赞扬的稿件也层出不穷，接下来就是铺天盖地的各方面纪念他的活动。
问题是这些活动真的这么多么？并没有，当时接到文件的时候满上海的找相关的活动进行报道，就是为了响应有关部门的文件。
2.内部部署 
其实和第一个类似，天朝很多情况下某种政策在推行起来有难度的时候都是借由媒体来吹风的，最典型比如延长退休年龄，比如以房养老，其实这些都是媒体先放出来的风。大家也许不接受，可是一年不接受，两年不接受，枕边风吹上个三年五年，甚至十年也未尝不可。
一鼓作气，再而衰，三而竭。民意亦然。
3.赞助
（1）公司对媒体
说白了就是软广告。媒体也要活着，要靠纯卖杂志来养活自己，那我估计现在的媒体也要死得差不多了，尤其是新媒体对纸媒冲击如此大的情况下，广告对于媒体收入至关重要。问题是，现在受众聪明了，硬广什么的渐渐也没什么吸引力了，软广既可以起到宣传的作用，本身也不那么让人讨厌，很多软广写的文笔简直赞到不行。
（2）公司对记者 
其实这个很好理解，媒体人也要活着，他们大部分的人其实没有大家想的那么光鲜亮丽，起得比鸡早睡得比小姐晚，其实很辛苦。这部分钱可以是车马费，以上海为例，有时候媒体记者从住的地方去现场单程两个小时家常便饭，来回要是公共交通要四个小时，如果刮风下雨打个车，单程100+也是很随意的，人家来跑个新闻，一个自己贴200+，也不现实吧。
还有就是软广，我认识一个在财经人物界很厉害的姐姐，她的软广4000RMB/每千字，关键是经常有人找她，没办法，人家软广告写的比很多杂志的封面人物还好，滴水不漏很难看出来是软广告，你看完她的文章就会敬佩文章中的人，但其实，这就是一篇宣传。

但我知道的是，有很多的媒体都是明令禁止记者收车马费的，所以说很多媒体还是业界良心，忍不住要点个赞！！！
3.记者的单纯发现
这个最好理解，新闻是对新近发生事实的报道，媒体记者凭着自己的新闻嗅觉去进行挖掘报道，这也是新闻最初的来源。

想插一句的是，大家不要觉得官媒里都是走狗都是政府喉舌，我遇到的XH社的一个老师为了帮助自闭症儿童，从最初到现在已经坚持了四年，并且仍然在坚持着，他可以算是我们国家现在媒体里对于自闭症儿童了解最多掌握资料最全的人，而这些，并没有任何的补贴，只是媒体人的责任感。

最后我想说的是，读懂新闻，很多时候需要你的头脑需要你自己去思辨去发现，说到底，受众能知道的事情都是媒体想让你们知道的，仅此而已。

不要觉得自己知道了所谓的真相，因为，那只是你以为的真相
* 大道至简，实际上最有用的方法最简单，就三步：行动，记录、总结（分析、思考、改进 
如果你从刚开始工作时就刻意的去记录自己所遇到的事情，包括正常工作、学到的经验，遇到的问题，每周或每月花了1、2天时间去分析自己的记录，不断的总结、分析和思考，你工作的一年时间可能比别人三年经验还要强，这个方法在目前我看到的所有行业和岗位中都适用。

拿程序员为例，大多数程序员前半年到一年左右成长提高的最快，2-3年时间可以从一无所知的菜鸟变成有丰富经验的技术经理，而很多人到达这个阶段之后就停止长成，如果没有特别的机会很能难继续成长为框架设计师。项目经理（独立带人完成整个项目，从前期到售后都包括在内）可能要2-3年左右，大约从5-10个普通程序员中出现一位。而一个好一点的核心构架设计师大约需要5-8年，经历并参加过二、三个大项目的核心设计，大致30-50个或上百个程序员中能出现一位。而这些人刚进入公司时，教育程度、水平、学习机会都相类似，但经过1-2年左右，就能看出差距所在。 
同样是五年经验的程序员，有的人是一年的经验重复了五年，有的人是五年，每周每月都在记录和总结中不断提高，一、二年可能差距不太大，3-5年的差距会大到难以想象。 

我觉得这三步是最主要和基础的，其他的，包括好奇心、兴趣、学习能力，阅读，积极主动、乐观、沟通能力、观察能力，只要这三步坚持下去都有所增强，至于能达到什么程度很难说，每个人投入的精力和时间不一样，关注的方向不一样，环境和心境也不同，比如刚参加工作、工作三年后和结婚后的表现又不一样。 

时间管理中用处最大的方法：柳比歇夫的时间统计法 

（1）总结：每天一小结，每月一大结，年终一总结。 

每天一小结 ：记下工作的起讫时间，误差不超过5分钟。 

不断看表,无休无止的进行自我工时标定。任何活动-休息、看报、散步，都记下时间，多少小时，多少分钟。小结所用的时间也奥记录。他的每篇论文都有时间成本。（多年来经常看表的结果，柳比歇夫肯定形成了一种特殊的时间感。借助于一种内在的注意力，感觉的到时间的流逝）--什么都记下起讫时间。 

他的日记很简短，只记和自己工作或自身相关的事。国家大事在上面基本没有反应。--记录所用语句很短 

每天临睡前进行时间统计。计算时间花在什么地方了，花了多少。最后算出基本消耗时间。每天只合计第一类的工作时间。（他每天的统计，结算，详细到了无情的地步，什么也不隐瞒，什么也不缩小。）--每天小结，睡前，纯时间的工作统计，总类统计，分类统计。 

计算的是纯时间，即刨除工作中的任何间歇。毛时间就是用在这项工作上的所有时间，包括毛时间和休息时间。 

每月小结，：将每天第一类工作时间合计出来，第二类的。等。然后是第一，二类的工作的一览表。借助图和表的形式。 

--每月小结，详细统计这月中的时间消耗。模式：总类，分类，详表。 

第一类的非常详细，第二类的同样非常详细。 

年终，根据月小结做份年度总结，列出一览表，旁边注着数字，又是加又是乘。要求进行自我分析、自我研究，效率有什么变化，为什么? 

年度总结：篇幅巨大，很详尽。什么记录都有。看了多少书，什么书，各国文字的文艺作品看了多少等。 

再统计一遍。把所有干了的，读了的，看了的统统收集到一起，加以计算，分门别类。一年来的工作和休息-简直什么事都要结算累计。例：娱乐-六十五次。接着列清单，列举看过的戏、电影、听过的音乐会、参观过的展览会 

年度总结有个欠债的账单，列着每月看完的书留下的尾巴。每年重复一次，没有减少。 

每份小结、总结的末尾都注明了他们的代价-花了多少小时多少分钟。 

个人总结 

：每天一小结，每月一大结，年终一总结。统计加比较分析。统计时间流向，比较两个阶段，分析原因 

--什么都记下起讫时间 

-记录所用语句很短 

--每天小结，睡前，纯时间的工作统计，总类统计，分类统计。 

--每月小结，详细统计这月中的时间消耗。模式：总类，分类，详表。 

年终总结，按总类、分类、详表的模式，统计这一年。并自我分析，研究。效率有什么变化，为什么。 

总结出自己的工作能力，找到适合自己的精力安排方式。 

例： 
乌里扬诺夫斯克。一九六四年四月八日。分类昆虫学：鉴 定袋蛾，结束–二小时二十分。开始写关于袋蛾的报告–一小时五分（1.0）。附加工作：给达维陀娃和布里亚赫尔写信，六页–三小时 二十分（0.5）。路途往返–0.5。休息–剃胡子。《乌里扬诺夫斯克真理报》–十五分， 《消息报》–十分，《文学报》–二十分；阿·托尔斯泰的《吸血鬼》，六十六页–一小时三十分。听里姆斯基-柯萨科夫的 《沙皇的未婚妻》 。基本工作合计–六小时四十五分。 这部分只是总结，他的计划部分也非常的强悍 

（2）计划：有月计划，年计划，五年计划。月计划先是通过时间统计法，了解到自己每天，每月能用于工作的时间有多少，以此为标准容器；通过时间统计法，还了解到自己做每样工作需要消耗的时间，于是以这两个标准，安排工作和活动。每天分为必须活动，非必须活动。睡觉，吃饭、这是必须的标准活动。一般约消耗十一二个小时；非标准活动，即办公、学术工作、娱乐等，约占十二至十三小时，这是毛时间。纯可利用时间是十小时，分成三个单位，或六个半单位。根据自己身体的节律，精神状态去安排工作、活动进行计划安排。这样每月预算三百小时。总结、计划占百分之一，顶多百分之二，即三到六个小时。计划就是挑时间，规定节律，使一切各得其所。用去的时间，应该同他从事的工作相称（我觉得是说时间花费的多少和工作的重要，紧急程度相符）。需要高深学识的工作，一天至多干七八小时。除最富于创造性的第一类工作，所有规定的工作量都竭力完成。第一类工作包括中心工作（写作、搞研究）和例行工作（看参考书、做笔记、写信等）。第二类工作包括做学术报告、讲课、开学术讨论会、看文艺作品，不属直接科研工作的活动都包括在内。我觉得，第一类工作和第二类工作的的分类方法，应该是以他要达到的生物学目标为标准。年计划总结完上一年，就该制定下一年计划了。下一年计划是根据柳比歇夫提出的任务大致安排的。五年计划除年度计划，他把一生时间，制定成一个个五年计划。每过五年，把度过的时间和干过的事分析一通，做个总的鉴定。做月计划，年计划，五年计划，总结时比对完成情况，原因是什么。
* 1.共情
其实这一点很多心灵鸡汤之类的东西都都提到了。如果你在一段对话中更多的扮演倾听者，同时又希望对方继续讲下去的话。可以大量的采用共情的方法。也就是“恩！我超级理解你”或者“你说的是不是这个意思”这类的话，上面这两种都是比较浅显的共情方法。在这讨论共情有长篇大论了。如果对方有很强烈的倾诉欲的时候，如果你一直将话题往自己身上引或者打断她的讲话，哦~亲！她是很不爽的！
如果你想结束和另一个人的对话，你最好实话实说。网络上有人说过，只要降低自己回复的活跃度，对方会自动结束对话，比如说一直说“哦”，这么做。。。朋友可能也快做不下去了。女神对屌丝的话，你只要呵呵就可以了。

2.强化
其实这个原理大家都懂，但是随着年龄的增长，越来越不会赞美别人。在强化的使用中包括正负两种。正强化就是常规所提到的一个人做对了一件事情要及时进行表扬，负强化则是指去除一个对他不利的因素。
这里还要提到的是惩罚，负惩罚就是常规提到的给与其不喜欢的因素，但是在教育或者日常生活中，要想达到惩罚目的，更舒缓的方法是负惩罚，即去除他喜欢的因素~~语言组织好像有问题~不过这段就是这么乱啦~~

3.投射
在寝室住的时候总有人吐槽别人书桌乱，吐槽别人晚上打扰别人睡觉，诸如此类，我们吐槽别人的时候，在吐槽之前可以悄悄反思一下，这些问题是不是也在我们身上发生。这些事情往往是因为在我们身上发生了，我们意识到这件事请对他人的影响，当意识到这个东西的时候，这个东西才存在。从这个角度来书，我们的意识是很唯心的。就相当你学到了“饕餮”这个词之后，你就会诡异的发现全世界都在使用这个词。并不是这个词忽然出现的，只是之前他出现的时候你还没有意识到他。
总之吐槽别人的时候，想想自己吧。
心理学的孩子们get这个技能之后，互相吐槽的时候就省力切高冷多了！
* 绘画的专业，随手写下
1.在看东西的时候会更倾向视觉而不是文字或者别的

2.读图（包括书法）跟读文字一样可以反复读（如果是好画的话可读性就强）

3.画画跟念书一样很耗脑力，会饿得很快。

4.说什么艺术是不慕名利的，说艺术非商业化的都是忽悠人的……其实艺术和金钱结合得特别特别紧密，看看草间弥生，炒得多生猛，跟LV互捧的姿势…；古代的西方，订画方都是要付上一笔钱；我国古代则有“润笔费”之说。（很多时候艺术圈也跟娱乐圈似的……）

5.大部分的时候画创作就跟写论文似得，要一步一步来，不排除有天才是即兴创作，而且还创作出非常牛的作品。什么灵感之类的是很偶然的，而且也要有之前的积累，很少有外人想象的都靠灵感。一挥而就什么的也很罕见，可能是一气呵成，但是不是一挥而就。

6.天赋一类的东西，个人认为要学得越深入才能越凸显，一开始没学好的话天赋很容易被磨掉…当然勤奋+努力也是必要的~（好像别的也是这个理？）

7.“艺术”这个词至今没法下定义。

8.那些拍卖会上买画卖画很多就跟投资买房似得，这不纽约前几天苏富比还是佳士得拍出一张培根的三联画八千万美元，十四十五年前卖家买入的时候是一千五百万美元，净赚五千多万美元……

9.由于专业训练和各种“职业病”，日常生活中会观察得比较细致。（咦，今天的光线和昨天好不一样啊！ 那个老奶奶的手好漂亮啊！春天到了绿色简直丰富到令人眼花缭乱啊！……之类的）

10.相机和人的感受真是差了十万八千里……

11.印刷品让人难以忍受（咦，好像越来越主观了…），但是现在的条件下也只能忍受了（事实上也买了不少画册QAQ）！因为a.绘画是立体的（不仅仅是油画，国画也是！）而印刷品是平面的！b.原作是有尺幅大小的，而印刷品你想印多大就多大…… 哀叹下萨金特、罗斯科的画……

12.我认为，画的好的人必定挖掘自己挖掘得很深，面对自己的时候很直接坦率。（所以放浪形骸的有之，进精神病院的有之，自杀的有之 ……吗？）

13.我认为，画的好坏，包括书法，和道德高低没啥直接关系。画能看出一个人的精神气，未必能看出品德这种太过于“约定俗成”的东西呢，个人看法……我觉得倒和性格很有关系。（想想前不久去世的佛洛依德，多么冷漠的一个…）

14.我认为， 看画的方法在于把脑中原来的概念清理掉，就是什么也不想，光看，好看就行。比方看习惯了日漫的人，就要去掉日漫的概念，不能觉得大眼睛尖下巴才好看，不能觉得好画的线条必须是顺畅的之类的；而看习惯古典油画的人，就要去掉古典油画带来的观念。

15.虽然对于很多颜色有专业术语，但是更多时候颜色是无法言说的。视觉的东西更是完全无法言说的——所以当我们交流这方面的时候就得对着画面，不然完全无法讨论——经过和圈外人的对比，发现作为视觉生物好像活在不同的世界里呢！（“站在这里一会儿吧，看过去好美啊！” “啊？啥啊？”或者“我拍一下这里马上就走！” “你不要什么都拍行不行啊！”或者“这个红色和那个红比起来感觉比较稳呢。” “我怎么觉得两个颜色一模一样？” “QAQ！明明完全不同啊！”——尽管发现了和其他人活着的世界是那么有差距还是想找个不画画的男盆友- - ——不过就算同是视觉生物似乎也不太在一个世界里……——“你看这画多好看~！” “……= = ” “= =…你不觉得吗……” “……反正我不喜欢= =。”）

16.都说画画的人很有个性，其实画画的人只是挖掘了自身，并坦率地表达了一下下（国人还是很多比较委婉的）…个人看法啦…

17.最烂俗的一句话，美就在身边，只是你的眼睛忽视了它~ ^ ^ 这是真的哦！

18.都说什么画画很感性，完全是瞎扯淡，看人的……不然咋还分冷抽象热抽象呢。不过我觉得有种性可以说，就是创造性哈~

19.学画画到现在受益最深的就是在不断学习跳出各种条条框框。（搞艺术的似乎道德观念更淡薄，几乎什么观念都觉得能接受大概也是因为这样吧…）

20.看起来再和前人不一样的画都是在前人基础上一步步发展来的，大家都是艺术史长河的一份子呀~
* 体制内的办事二法：
(以下引自《厚黑学》) 
1．锯箭法 
有人中了箭，请外科医生治疗，医生将箭干锯下，即索谢礼。问他为什么不把箭头取出？他说：那是内科的事，你去寻内科好了。这是一段相传的故事。
现在各军政机关，与夫大办事家，都是用的这种方法。譬如批呈词：“据呈某某等情，实属不合已极，仰候令饬该县知事，查明严办。”“不合已极”这四个字是锯箭干，“该知事”是内科，抑或“仰候转呈上峰核办”，那“上峰”就是内科。又如有人求我办一件事情，我说：“这个事情我很赞成，但是，还要同某人商量。”“很赞成”三字是锯箭干，“某人”是内科。又或说：“我先把某部分办了，其余的以后办。”“先办”是锯箭干，“以后”是内科。此外有只锯箭干，并不命其寻找内科的，也有连箭干都不锯，命其径寻内科的，种种不同，细参自悟。

2．补锅法 
做饭的锅漏了，请补锅匠来补。补锅匠一面用铁片刮锅底煤烟，一面对主人说：“请点火来我烧烟。”他乘着主人转背的时候，用铁锤在锅上轻轻的敲几下，那裂痕就增长了许多，及主人转来，就指与他看，说道：“你这锅裂痕很长，上面油腻了，看不见，我把锅烟刮开，就现出来了，非多补几个钉子不可。”主人埋头一看，很惊异的说：“不错！不错！今天不遇着你，这个锅子恐怕不能用了！”及至补好，主人与补锅匠，皆大欢喜而散。

郑庄公纵容共叔段，使他多行不义，才举兵征讨，这就是补锅法了。历史上这类事情是很多的。有人说：“中国变法，有许多地方是把好肉割坏了来医。”这是变法诸公用的补锅法。在前清宦场，大概是用锯箭法，民国以来，是锯箭、补锅二者互用。 

* 生命已经这么短了，为什么大多数人还是流于世俗而不追求真正想
个人层面：很多人，夸大了未来的恐怖之处，并过于高估了自己的主观能动性，这就导致他们陷入了一个漩涡里：越上不去越焦虑，越焦虑越想上去，自己实在上不去生个孩子拼命想让孩子上去；
社会层面：非体制内人士几乎无任何保底和退路使得人人自危。
教育层面：不教健全的人格，不教健康的身体和心理，不教如何赚钱，不教社会运行的真实逻辑，反而灌输的只是完全脱离实际和应用的知识，教的是等级观念和服从意识，培养的是焦虑紧张的心态。为什么贩卖焦虑有这么大市场？因为大部分人接受的教育模式，就是贩卖焦虑。绝大部分人从小就在焦虑之中，周围人每天720°以各种方式高强度告诉你，你学习不好/工作不好/长的不好/情商不行/不吃苦/不买房/不结婚/不努力……，你要完了。
“完”是确实会“完”，但真实原因不是你不优秀或者不努力，
而是：食利阶层联合起来绞杀原子化的底层，并树立起几个爬上去的典型，不断挑拨底层互斗，使得底层无法团结起来，对抗真正的敌人。
