
* b
info b: 查看所有
del 8: delete 第8个断点
b : 无参数，在当前行设置断点

* step out fin(ish)
* p
(gdb) p/x mask      # 十六进制
(gdb) p/t mask      # 二进制（GDB 7.7及更高支持）
如果gdb 版本不支持p/tj
(gdb) python print(bin(gdb.parse_and_eval("mask")))
* break foo.cpp:123 if std::string(dir.c_str()) == "./CMakeFiles"
some GDB versions don’t fully support std::string in conditional breakpoints.
b fd4.cpp:138 if strcmp(dir.string().c_str(), "tdir/cpp_fd4.dir/src") == 0

* if object printing looks messy.
set print pretty on

if object printing looks messy.
watch dir
But for C++ objects, this watchpoint might not work (complicated for structs/classes).
* look up array
*array@length

display *a@5
undisplay 显示的号码
* enhanced
gdb-peda
gdb-pwndbg
gdb-gef

* GDB TUI Mode (Visual Highlighting)
已经进入gdb, 运行 layout src -->tui
Ctrl-x a       # 切换 TUI/非 TUI

ctrl p : get history command

gdb -tui ./your_program
The current line is highlighted in the source code window.

Press Ctrl + L to refresh if the display gets corrupted.

** frame: show current line number
** list *$pc
show current instruction line
