一周做到2-3更新，保持一定的账号活跃度就可以了
就是做垂直深耕
笔名，就成为一个写作IP，会辐射出多个盈利渠道

光是单纯的读书，其实对写作没啥帮助，除非你将读书和思考相结合

1.她的段子取材皆来源于生活，观众熟悉，有共鸣
2.通过“逻辑重构”来实现“预期违背”


锻炼表达能力的最好方法，就是去阅读之后复述。

如果复述做不到，就去学着将刚才所学习到的东西，用自己的话来解释清楚！

用大白话，来对着空气去解释这个概念，直到解释清楚为止。


* 平台
今日头条

（可发图文/短视频/微头条/图集/付费专栏/小说，图文末尾可加联系方式，可得青云计划拿300元-1000元奖金/每篇，盈利渠道最多，多达14种，各个好用，推荐！）

悟空问答

（可提问，可回答问题，开通问答收益后，回答问题可以赚钱，可获得问答青云计划）

bilibili

（可发视频/文章，收益好，用户素质相对较高，氛围好，前景不错，盈利渠道以平台分成和广告费为主，推荐！）

阿里创作平台

（可发文章，可发短视频，可投稿，可接任务，盈利渠道以商品分销为主）

知乎

（流量大，用户优质，内容收录好，可回答问题，可创建专栏，可以发布视频，可创建知乎Live赚钱，可签约，文末可加联系方式，盈利渠道为商品分销，自接广告，付费咨询等，推荐！）

百家号

（可发文章/短视频/图集，收益单价相对较高，盈利渠道为平台收益分成和商品功能分销）

企鹅号

（可发文章/短视频/图集，原创且独家收益单价高）

大鱼号

（可发文章/短视频/图集，短视频打通了优酷和土豆网渠道，各种奖励和签约计划不错）

趣头条

（可发文章/短视频/图集，单价不错）

搜狐公众平台

（可发文章/短视频/图集，文章末尾可加联系方式，内容排名好，有分成计划和麦芒计划）

一点号

（可发文章/短视频/图集）

爱艺奇号

（可发文章/视频，泡泡圈流量大）

百度经验

（新回享计划，可拿现金稿酬，可以将文章同步）

豆瓣

（流量优质，内容收录排名好，可写日记/书评/影评/读书笔记，发小组贴等，文末可加联系方式，可发表电子书赚钱，也可吸粉，间接变现，推荐）

新浪微博

（可发微博/视频/头条文章，文末可加联系方式）

简书

（可发文章，可发付费文章/付费连载）

抖音

（流量大，可发小视频，可通过接广告，商品功能赚钱，推荐）

小红书

（流量不错，可发短视频/文章，接广告赚钱，推荐）

知识星球

（可发文章，可创建圈子，可做付费社群赚钱）

喜马拉雅FM

（可发音频，可创建圈子发贴，盈利渠道以广告分成、付费音频、付费音频分销为主，推荐）

企鹅FM

（可发音频，盈利渠道以付费音频、签约、用户打赏为主）

荔枝FM

（可发音频，盈利渠道以音频直播、签约、付费音频为主）

荔枝微课

（可个人授课，通过销售付费课程赚钱）

百度网盘

（可通过销售资料赚钱）

百度文库

（可上传图文资料，专家名师认证和文章作者认证，盈利渠道为付费文档销售、广告分成收益）

腾讯课堂

（在线教育平台，可个人授课赚钱，也可分销课程赚钱）

微信公众号

（可发表图文/音频/短视频，还可以发表付费文章，盈利渠道以接广告、粉丝变现为主，最近推出视频号，可以视频号推广吸粉，公众号付费文章变现）


* read
** 克苏鲁神话
<span class="RichText ztext CopyrightRichText-richText css-yvdm7v" options="[object Object]" itemprop="text"><p data-first-child="" data-pid="ynQQUg8V">爪机打字就不打书名号了。。。</p><p data-pid="FoRpt4Qi">合集的话有邪神复苏和恐怖人间两本可选。</p><p data-pid="mVg5DiA7">短篇的话，推荐阅读：</p><p data-pid="eDNdINag">黄色印记（力荐）</p><p data-pid="d45iG9Uq">魔女屋中之梦</p><p data-pid="qozlq9-U">超越时间之影（力荐）</p><p data-pid="7IZqhKmq">银钥匙（力荐）</p><p data-pid="-vVrJlcw">疯狂山脉（力力力荐）</p><p data-pid="jVGZrMm5">自外而来</p><p data-pid="_wYTbfXa">绿字的研究（力力力力力荐）</p><p data-pid="TctXxSyz">穴中怪兽</p><p data-pid="tZNWBck3">暗夜呢喃（力荐）</p><p data-pid="qtB-jQmC">星之彩</p><p data-pid="1kyWlZYi">墙中之鼠（力荐）</p><p data-pid="f-xSNjzc">异乡人</p><p data-pid="Dm7JcJTB">乌撒的猫</p><br><p data-pid="TqqU24Ko">最后，欢迎题主来到克苏鲁的世界。愿旧日支配者安息。</p></span>
