* 网络，IO，容易出错的代码要try & catch
* 优秀程序员思考、学习新技术的原则和方式
最近了解了几个 MVC 的框架，其中有两个是公司内部的。发现这些东西都是类似的，从处理
逻辑到页面渲染；从 service 到 layout；配置的实现无非就是 XML，或者 annotation……
我有种感觉，兴许已经跳不出这个思维圈子了？

他们却缺乏这样一种能力——思考。

欠缺思考容易导致这样的现象：

不会做设计

遇到了问题，拿见到过的、学到了的熟悉的框架、方案、模式往上套，而不仔细分析其中的
利弊，只是尽可能地寻找最接近当前问题的解决途径。

还有的则是不会做面向对象设计，缺少抽象和解耦的能力，这样的例子就更多了。朋友告诉
我，他的单位有一位写 Ruby 的老员工，一个庞大的工程，代码里面居然只有一个上帝类，
就搞定了所有的问题。

不能坚持自己的观点

这一点在面试中最容易观察到。应聘者有刚毕业的学生，也有工作超过 10 年的有丰富经验
的从业者。他给出一个粗略的方案以后，在方案没有细化到一定程度以前，很难给出优劣的
评论，但是，如果你轻轻地 challenge 一下，他就迅速放弃本来的构思，跑到你的思路上来。

例如，SNS 系统中，服务端有消息要怎样通知到客户端，这样的一个问题，解决方案有很多
种，比如客户端轮询、服务端 hold 住连接推送等，各有利弊。应聘者应当有自己的观点。

不能细化一个问题解决方案

怎样区分一个空谈家和一个实干家？给他一个具体的问题是最好的办法。在我刚工作的时候，
我曾经很钦佩那些在活动中、讨论中高谈阔论的人，我觉得他们很能说。可是后来我逐渐发
现，能说的人实在是太多太多了。细化设计、甚至落到编码，才是对一个程序员真实的检验。
当然，如果你觉得做软件设计的人可以不熟悉编码、架构师可以不首先是一名高级程序员，
那我们也没有什么可谈了:)。

如果你会学习，你可以成长得很快；如果你不会思考，你永远只能跟在别人后面。

在新技术的学习上我认为也应当多思考，不同的人有不同的学习动机。在非外界所迫的情况
下，对于新技术的学习，我的观点可以概括为：

它要解决什么问题，就是所谓的问题域，是我关心的吗？

我没有去研究操作系统底层的实现，并非这没有价值，而是我没有兴趣，这就是问题域的影
响（不过现在我有兴趣了，我想做一些这方面的事情）。

和过往解决方案它的优势在哪里，是否显著？

这是 competition，重复的技术是没有生存空间的（当然，你是微软的话除外:)），就像互
联网同一个类型的网站，竞争到最后就那么两三家。就像 Groovy，我很喜欢它，但是有了
Scala 以后，我觉得兴许有一个要死掉（Groovy 创始人说，如果他早些知道 Scala 的话，
就没有 Groovy 什么事了。具体的报道请去 Google 上搜他的 blog）。

　　它的实现和带来的效果上看，有没有很有意思的思路，是值得借鉴和思考的？

这是最难讲的一个问题。以去年初开始接触的 Node.js 为例，它可以做到把后端的聚合（譬
如 portlet 之流）放到前端来，后端只保留一种类型的页面服务——页面模板，以及若干易于
管理的 API 接口，大大简化了后端体系的复杂度，而且还能把压力分散到前端来，这是我早
些年不曾见到的。

这三个问题想过之后，觉得有价值，我才去学习。要不然，对我而言就是不想深入的东西，
了解了解也就罢了。

新技术学习的方式呢，我想说这么几点：

寻找切入点

我很喜欢 BlueDavy 的 blog 上的一句话：“理论不懂就实践，实践不会就学理论！”。

最后最好是要落到动手实践上去的，但是倘若习惯从那些原理介绍的文字入手，未尝不是一
种不好的选择。而且，现实情况会有一些约束，例如在了解几家互联网公司的云平台的时候
（Amazon 的 EC2，M$的 Azure 等等），除非你是这几家公司的员工，否则是很难深入其中
的。

寻找自己的兴趣点

善于比较

不断获得回馈

回馈是什么？做出一个 HelloWorld 的例子，就是一个极好的回馈；理解某一项实现原理，
联想到其它类似的实现，产生一种恍然大悟的感觉，也是一种回馈。在学习的过程中，不断
产生回馈，意味着你不断地收获成就感，这是继续下去的动力之一。

* 一名程序感悟：
抽象。计算机中的oop编程。处理任何问题时不要只看到表面，要不停的思考，再抽象一个层次，更能接近事物的本质。
预读。计算机中操作系统预读可以有效的减少磁盘的寻道次数和应用程序的I/O等待时间。生活中也是，凡事预则立不预则废。
缓存,缓冲。计算机中操作系统中硬件经常用的。两个极端不匹配的东西放到一起时就要做缓冲，缓存等。
分治。计算机中的快排等都用到分治。就是麦肯锡的mece原则,沟通做事都可采用。分解问题，各个击破。
贪心。计算机中的贪心算法。处理事情时候也是如此，抓大放小。
做人做事的：
无论是温总理的”仰望星空与脚踏实地“，还是王国维的“入乎其内，故有生气，出乎其外，故有高致”。还是金出武雄的”像外行一样思考，像专家一样实践“，其实就就简单的四个字，“能屈能伸”。

* signalled and not
Every waitable object has a boolean value attached to it, named the signalled state, that is used to wait for that object; if the object is signalled, then the wait functions will not wait for it; if the object is non-signalled, then the wait functions will wait for it.

Now, how does this apply to a particular type of object? That depends on the objects nature and specifically on the semantics associated to waiting for it. Actually, the signalled state is defined in terms of wait condition. the For example (see the docs for details):

A mutex is signalled when it is not owned.
An process/thread is signalled when it has finished.
A semaphore is signalled when its count is greater than 0.
A waitable timer is signalled when it has expired.
You might like better if a mutex were signalled when owned, but actually it is when not owned. That's necessary to make the wait functions do the right thing.

And what about the events? Well, they are somewhat simple objects, you can signal and de-signal them at will, so the signal state has no additional meaning:

signalled: Threads will not wait for it.
non-signalled: Threads will wait for it.
Events also have this SignalPulse and AutoReset things that are a bit peculiar (and IME practically impossible to use right).
* 阻塞/非阻塞 能不能专心干其他事情  (等待消息通知时的状态 )
