* sql>\d dlx_test
CREATE TABLE "sys"."dlx_test" (
        "a_data_topbi_user_id"    INTEGER,
        "a_data_topbi_user_name"  CHARACTER LARGE OBJECT,
        "a_data_topbi_sex"        INTEGER,
        "a_data_topbi_nation"     CHARACTER LARGE OBJECT,
        "a_data_topbi_city"       CHARACTER LARGE OBJECT,
        "a_data_topbi_province"   CHARACTER LARGE OBJECT,
        "a_data_topbi_salary"     INTEGER,
        "a_data_topbi_rank"       DOUBLE,
        "a_data_topbi_deposit"    INTEGER,
        "a_data_topbi_cost"       INTEGER,
        "a_data_topbi_date"       TIMESTAMP,
        "a_data_topbi_career"     CHARACTER LARGE OBJECT,
        "a_data_topbi_race"       CHARACTER LARGE OBJECT,
        "a_data_topbi_school"     CHARACTER LARGE OBJECT,
        "a_data_topbi_college"    CHARACTER LARGE OBJECT,
        "a_data_topbi_speciality" CHARACTER LARGE OBJECT,
        "a_data_topbi_grade"      CHARACTER LARGE OBJECT,
        "a_data_topbi_mark"       INTEGER,
        "a_data_topbi_highest"    INTEGER,
        "a_data_topbi_lowest"     INTEGER,
        "a_data_topbi_open"       INTEGER,
        "a_data_topbi_close"      INTEGER
);

* taskkill /F /IM mserver5.exe & taskkill /F /IM mclient.exe & nmake /nologo /f ..\NT\Makefile "prefix=D:\MonetDB\2015mt-bin" 

MAKE_INCLUDEFILE=D:\MonetDB\svn\monet_switchp & nmake /nologo /f ..\NT\Makefile "prefix=D:\MonetDB\2015mt-bin" 

MAKE_INCLUDEFILE=D:\MonetDB\svn\monet_switchp install

taskkill /F /IM mserver5.exe & taskkill /F /IM mclient.exe & nmake /nologo /f ..\NT\Makefile "prefix=D:\MonetDB\2015mt-

bind" MAKE_INCLUDEFILE=D:\MonetDB\svn\monet_switchd & nmake /nologo /f ..\NT\Makefile "prefix=D:\MonetDB

\2015mt-bind" MAKE_INCLUDEFILE=D:\MonetDB\svn\monet_switchd install

taskkill /F /IM mserver5.exe & taskkill /F /IM mclient.exe & nmake /nologo /f ..\NT\Makefile "prefix=D:\MonetDB\2015mt-

bind" MAKE_INCLUDEFILE=D:\MonetDB\svn\monet_switchd & nmake /nologo /f ..\NT\Makefile "prefix=D:\MonetDB

\2015mt-bind" MAKE_INCLUDEFILE=D:\MonetDB\svn\monet_switchd install

How to instruct linux not to swap out hot pages of mmaped files
What you probably need is mlock(), not madvise(). Madvise is too 'weak'; mlock locks the memory in the kernel. Assuming you 

have enough RAM and only lock the 'hot' pages (not the whole 8GB) that shouldn't be a problem for your setup.

编译debug版本，要新建 build (d_build) 和 install (d_install) 目录

configure.ac:70: error: Could not locate the pkg-config autoconf
    macros. These are usually located in /usr/share/aclocal/pkg.m4.
    If your macros are in a different location, try setting the
    environment variable M4DIRS="-I/other/macro/dir" before running
    ./bootstrap or autoreconf again.
solution: export ACLOCAL_PATH=/usr/share/aclocal/

"PCRE Library Not Found" error can also be caused when the pcre package is installed but not the pcre-devel package.
libxml2 library not found : yum install libxml2-devel
bz2 library not found: bzip2-devel

nmake /nologo /f ..\NT\Makefile "prefix=D:\MonetDB\mt-bin" MAKE_INCLUDEFILE=D:\MonetDB\svn\monet_switch 

NO_PYCOND=1 NO_TESTING=1 NO_BUILDTOOL=1 NO_GDK=1 NO_CLIENTS=1 NO_COMMON=1 NO_GEOM=1 NO_SQL=1 

NO_MONETDB5=1 NO_TOOLS=1

NO_PYCOND=1 NO_TESTING=1 NO_BUILDTOOL=1 NO_GDK=1 NO_CLIENTS=1 NO_COMMON=1 NO_GEOM=1 NO_TOOLS=1

NO_PYCOND=1 NO_TESTING=1 NO_BUILDTOOL=1 NO_CLIENTS=1 NO_COMMON=1 NO_GEOM=1 NO_SQL=1 

NO_MONETDB5=1 NO_TOOLS=1

Makefile.am:27: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:27:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:27:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:27:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:27:   its definition is in aclocal's search path.
用的是1.15的automake, libtool 2.2.6 
libtool 版本升级到 2.4.6就可以了(wget http://ftpmirror.gnu.org/libtool/libtool-2.4.6.tar.gz)。

http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz
http://ftpmirror.gnu.org/libtool/libtool-2.4.6.tar.gz

或者用1.11的automake

libtoolize
aclocal && autoheader && autoconf
automake --add-missing

# autogen.py scans the makefile.ag
# and generates both the makefile.am and makefile.msc

automake use Makefile.ag to produce Makefile.in