  hosts: worker_servers
  # copy /home/lzy/testip.yml to /home on all worker_servers except bdnode1
  #gather_facts: false
  tasks:
    - name: copy to remote
      copy:
        src: "/home/lzy/testip.yml"
        dest: "/home/"
        force: no
      when: ansible_hostname != 'bdnode1'
